Create numbers from 0 to 9 using arange.

Create numbers from 1 to 20 with step 2.

Create negative numbers using arange.

Create numbers from 10 to 1 in reverse order.

Create a range starting from 5 to 50 with step 5.

Create decimal numbers using arange.

Observe floating point errors using arange.

Create an array of even numbers below 100.

Create an array of odd numbers below 50.

Use arange to create index values.

Create a 2D array using arange and reshape.

Create time intervals using arange.

Create an array and count its length.

Why does arange(0,1,0.1) sometimes give unexpected length?

Create values excluding the stop value.

Create a decreasing sequence.

Use arange for loop replacement.

Create a large array using arange and check speed.

Use arange for slicing reference.

Decide when arange should NOT be used.


In [1]:
import numpy as np

In [3]:
# 1.
num = np.arange(10)
num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 2.
num1 = np.arange(1,21,2)
num1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
# 3.
num2 = np.arange(0,-10,-1)
num2

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [9]:
# 4.
n = np.arange(10,0,-1)
n

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [10]:
# 5.
m = np.arange(5,51,5)
m

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
# 6.
n1 = np.arange(0,10,0.7)
print(n1.dtype)
print(n1)

float64
[0.  0.7 1.4 2.1 2.8 3.5 4.2 4.9 5.6 6.3 7.  7.7 8.4 9.1 9.8]


In [31]:
# 7.
n2 = np.arange(0,10,1.5)
n2
# error is : 
# 1. Observing the Cumulative Error
# If you print the values of np.arange with high precision, you can see that the numbers are not exactly what they appear to be.
# 2. The "Endpoint" Problem
# The most dangerous part of using arange with floats is that you cannot guarantee whether the stop value will be included or excluded. 
# Because of the precision drift, the final sum might be slightly above or below your "stop" threshold.

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [33]:
# 8.

even = np.arange(0,100,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [36]:
# 9.
odd = np.arange(1,50,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [39]:
# 10.
ind = np.arange(10)


In [43]:
# 11.
even.reshape(5,10)


array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [ ]:
# 12.
interval = np.arange(0,60,10)
interval  # 10 sec interval


array([ 0, 10, 20, 30, 40, 50])

In [ ]:
#13.
GAP = np.arange(0,1,0.1)
GAP
# somtimes gives unexpected length
# answer give in 7th question

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [49]:
# 14.
len(interval)

6

In [ ]:
# 15.

arr = np.arange(10000)
for i in arr:
    print(i)

In [ ]:
a = np.arange(0,21,2)
data = arr[a]  # a use a reference index 
print(data)

[ 0  2  4  6  8 10 12 14 16 18 20]


Here is the clean Markdown code for you. You can copy the block below and paste it directly into a Markdown cell in your Jupyter Notebook or Colab.

---

# When to Avoid `np.arange`

While `np.arange` is powerful, it isn't always the right tool for the job. Here are the four main scenarios where you should look for an alternative.

---

### 1. The Floating-Point Drift Problem

Computers represent decimal numbers in binary, which leads to tiny rounding errors. If you use a floating-point step (like `0.1`), these errors accumulate.

**The Risk:** You might end up with an unexpected number of elements because the "stop" value is slightly off in memory.

* **Better Alternative:** Use `np.linspace(start, stop, num)`. You define exactly how many points you want, and NumPy calculates the step size precisely to fit.

### 2. When the Endpoint is Required

By default, `np.arange` uses the interval , meaning the **stop value is excluded**. If your model requires the sequence to end exactly at a specific boundary, `arange` is awkward because you have to "overshoot" the stop value to include it.

* **Better Alternative:** `np.linspace` includes the endpoint by default, making it much more intuitive for inclusive ranges.

### 3. Simple Iteration (Memory Waste)

If you are just writing a basic `for` loop to repeat a task and don't need to do array-wide math, **don't use NumPy**.

* `np.arange` creates the entire array in your RAM immediately.
* The built-in `range()` is a **generator**; it only creates one number at a time as the loop asks for it, saving significant memory.

> **Rule of Thumb:** If you aren't doing vectorized operations (like `arr * 2`), stick to the standard Python `range()`.

### 4. Simple Slicing Patterns

If you already have an array and want every second element, creating an index map with `arange` is redundant and slower than native slicing.

* **Avoid:** `data[np.arange(0, len(data), 2)]`
* **Use:** `data[::2]` (Standard Python Slicing)

---

### Quick Reference Table

| Scenario | Use `np.arange` | Use `np.linspace` | Use `range()` |
| --- | --- | --- | --- |
| **Integer steps** | ✅ Best choice | ❌ Overkill | ❌ Loops only |
| **Fixed number of points** | ❌ Math-heavy | ✅ Best choice | ❌ No |
| **Floating point steps** | ⚠️ Risky | ✅ Safe | ❌ No |
| **Basic `for` loops** | ❌ Memory heavy | ❌ Memory heavy | ✅ Best choice |

---

**Would you like me to generate a Python code snippet that demonstrates the floating-point error so you can see it in action?**