Create a 3×3 identity matrix.

Create a 5×5 identity matrix.

Multiply identity matrix with another matrix.

Add identity matrix to another matrix.

Create a non-square identity-like matrix.

Use eye() to initialize weights.

Extract diagonal values from identity matrix.

Replace diagonal values in identity matrix.

Explain why identity matrix is important.

Where would you use eye() in machine learning?

In [1]:
import numpy as np

In [2]:
1.
e = np.eye(3)   # identity matrix
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
2.
e = np.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
a = np.linspace(0,100,25,dtype=int)
a = a.reshape(5,5)
e = e + a
e

array([[  1.,   4.,   8.,  12.,  16.],
       [ 20.,  26.,  29.,  33.,  37.],
       [ 41.,  45.,  51.,  54.,  58.],
       [ 62.,  66.,  70.,  76.,  79.],
       [ 83.,  87.,  91.,  95., 101.]])

In [5]:
e = e * a
e

array([[    0.,    16.,    64.,   144.,   256.],
       [  400.,   650.,   841.,  1089.,  1369.],
       [ 1681.,  2025.,  2550.,  2916.,  3364.],
       [ 3844.,  4356.,  4900.,  5700.,  6241.],
       [ 6889.,  7569.,  8281.,  9025., 10100.]])

In [7]:
3.
i = np.eye(3)
matx = np.array([[1,2,3],[4,5,6],[7,8,9]])

mul = matx * i
mul

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [8]:
4.
addition = matx + i
addition

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [11]:
5.
i2 = np.eye(N=3,M=4)
i2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
6.
i3 = np.eye(4) * 10 # weighted identity matrix
i3

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [26]:
7.
i4 = np.eye(3) * 5
s = min(i4.shape)
a = np.zeros(s)
for i in  range(len(i4)) : 
   
    a[i] = i4[i][i]
print(a)

# OR 

diagnol = np.diag(i4)
diagnol

[5. 5. 5.]


array([5., 5., 5.])

In this specific context, `min()` is acting on the **dimensions** of your matrix to determine the maximum possible length of the diagonal.

Here is the breakdown of how those two lines work together:

### 1. What is `i4.shape`?
In NumPy, `.shape` returns a **tuple** containing the number of rows and columns. 
* If `i4` is a $3 \times 5$ matrix, `i4.shape` is `(3, 5)`.
* If `i4` is a $10 \times 2$ matrix, `i4.shape` is `(10, 2)`.

### 2. How `min()` processes that tuple
When you write `min(i4.shape)`, Python looks at the numbers inside that tuple and picks the smallest one.

* **Example A (Wide Matrix):** If your matrix is $3 \times 5$, `min(3, 5)` returns **3**. 
* **Example B (Tall Matrix):** If your matrix is $10 \times 2$, `min(10, 2)` returns **2**.

### 3. Why is this necessary?
The diagonal of a matrix can only be as long as its **shortest side**. 



If you have a $3 \times 5$ matrix and you tried to find a 4th diagonal element, the code would look for the value at row index 3 and column index 3. However, since there are only 3 rows (indices 0, 1, 2), your program would crash with an `IndexError`. 

By using `s = min(i4.shape)`, you ensure that:
1. **`s`** is the correct length of the diagonal.
2. **`np.zeros(s)`** creates an array exactly big enough to hold those diagonal values.
3. Your loop (which likely uses `range(s)`) never tries to access a row or column that doesn't exist.

### Summary of the logic:
```python
i4 = np.eye(3, 5)  # A 3x5 matrix
shape_tuple = i4.shape  # This is (3, 5)
s = min(shape_tuple)    # s becomes 3
a = np.zeros(s)         # Creates array([0., 0., 0.])
```

This prevents the "falling off the edge" problem we discussed earlier when dealing with **non-square matrices**.


In [27]:
8.

i5 = np.eye(5)
a = np.array([23,41,51,34,25])
i5 = i5 * a
i5



array([[23.,  0.,  0.,  0.,  0.],
       [ 0., 41.,  0.,  0.,  0.],
       [ 0.,  0., 51.,  0.,  0.],
       [ 0.,  0.,  0., 34.,  0.],
       [ 0.,  0.,  0.,  0., 25.]])

9. Explain why identity matrix is importent ?


ans - The identity matrix, denoted as $I$, is often called the "**number 1 of the matrix world**." Just as $5 \times 1 = 5$, any matrix multiplied by the identity matrix remains unchanged ($A \times I = A$).

While that sounds simple, this property makes it a cornerstone of linear algebra and computer science. Here is why it is so important:

---

### 1. The Multiplicative Identity
In regular math, the number **1** is the neutral element for multiplication. In the world of matrices, where "division" doesn't technically exist, we need a neutral starting point for operations.

$$A \cdot I = A$$
$$I \cdot A = A$$

This allows mathematicians to manipulate complex equations without changing the core values of the data.

### 2. Finding the Inverse ($A^{-1}$)
The identity matrix is the goal of matrix inversion. To find the "opposite" of a matrix, we look for a matrix that, when multiplied by the original, results in the identity matrix:
$$A \cdot A^{-1} = I$$

This is crucial for solving systems of linear equations ($Ax = b$). If you can turn $A$ into $I$, you have essentially isolated your variable and solved the problem.

### 3. Coordinate Transformations (Computer Graphics)
In 3D modeling and video games, matrices represent movements like rotation, scaling, or translation.
* **The Identity Matrix represents the "Zero State."** * It means no rotation, no movement, and no change in size.
* When a developer "resets" a camera or an object’s position, they are usually resetting its transformation matrix to the Identity Matrix.



---

### 4. Eigenvalues and Eigenvectors
In engineering and physics, the identity matrix is used to find the "characteristic equation" of a system. To find the eigenvalues ($\lambda$), we solve:
$$\det(A - \lambda I) = 0$$
Without the identity matrix, we wouldn't be able to subtract a single number (a scalar) from a grid of numbers (a matrix). The identity matrix "stretches" that single number across the diagonal so the math works.

### 5. Neural Network Initialization
In Artificial Intelligence, "Identity Initialization" is a technique where weights are set to the identity matrix. This ensures that at the start of training, the signal passing through the layers doesn't get distorted or lost—it passes through perfectly "clean" before the model starts learning how to change it.

---

### Summary: Why we need it
| Concept | Role of Identity Matrix |
| :--- | :--- |
| **Arithmetic** | Acts as the number "1". |
| **Algebra** | Necessary to define the inverse ($A^{-1}$). |
| **Geometry** | Represents the "default" or "no change" state. |
| **Physics** | Allows us to solve for system stability (Eigenvalues). |

Think of it as the **neutral gear** in a car—it’s the reference point from which all other movements are measured. 

Does this help you see how it fits into the bigger picture of your matrix calculations?


10.  Where would you use eye() in machine learning? 

**why use eye() in machine learning ?**
In machine learning, `np.eye()` is used to create an **Identity Matrix** (), a square matrix with ones on the main diagonal and zeros elsewhere. This structure is a fundamental tool for data encoding, model stability, and mathematical transformations.

Here are the primary reasons you would use it:

### 1. One-Hot Encoding

The most common "entry-level" use for `eye()` is converting categorical labels into a format a model can understand. By indexing an identity matrix, you can instantly turn a class index (like `2`) into a binary vector (like `[0, 0, 1]`).

```python
import numpy as np
categories = np.array([0, 1, 2, 1])
# Create 3x3 identity and index it with our labels
one_hot = np.eye(3)[categories]

```

### 2. Weight Initialization in Neural Networks

While many networks start with random weights, some architectures benefit from **Identity Initialization**.

* **RNNs/LSTMs:** Initializing hidden-to-hidden weights as an identity matrix helps information persist over long sequences, preventing gradients from vanishing.
* **Residual Networks (ResNets):** It ensures that, at the start of training, the layer's output is nearly identical to its input, making the "residual" easier to learn.

### 3. Ridge Regression (L2 Regularization)

In Ridge Regression, the "closed-form" solution requires adding a small value to the diagonal of a matrix to ensure it can be inverted. The formula is:



Here,  (created by `eye()`) acts as a "stabilizer" that prevents the model from over-relying on any single feature, effectively reducing overfitting.

### 4. Dimensionality Reduction (PCA)

In Principal Component Analysis, the identity matrix is often used when calculating the **Covariance Matrix** or when performing "whitening" transformations. It serves as the baseline "unit" for variance across different dimensions.

### 5. Numerical Stability

Sometimes a matrix is **singular** (it cannot be inverted). By adding a tiny multiple of the identity matrix (e.g., ), you "nudge" the matrix into being invertible without significantly changing the data. This is a common trick in Gaussian Processes and optimization algorithms.

---

| Use Case | Role of `eye()` | Why? |
| --- | --- | --- |
| **Data Prep** | One-Hot Encoding | Maps integers to unique binary vectors. |
| **Regularization** | Ridge Regression | Adds a penalty to the diagonal to prevent overfitting. |
| **Deep Learning** | Identity Initialization | Helps signals flow through deep layers without dying. |
| **Linear Algebra** | Matrix Inversion | Ensures matrices are "well-behaved" and solvable. |

Would you like to see a comparison of how Identity Initialization affects the training speed of a simple Recurrent Neural Network (RNN)?

[The Identity Matrix - Explained](https://www.youtube.com/watch?v=8gHrydSXQQ8)
This video explains the mathematical properties of the identity matrix and why it serves as the "do-nothing" baseline for transformations in machine learning.
