Create a 1D array of ones with length 8.

Create a 2D array of ones with shape (4, 5).

Create a 3×3 matrix of ones.

Create a ones array and multiply it by 10.

Create a ones array and add it to another array.

Create a ones array and use it as a multiplier.

Create a ones array with float dtype.

Create a ones array with integer dtype.

Create a ones array and subtract values from it.

Create a ones array and reshape it into (2, 3).

Use ones to create a bias vector.

Create a ones array and check memory size.

Create a ones array and convert it to zeros.

Create a ones array and apply boolean conditions.

Explain why ones are useful in normalization.

In [1]:
import numpy as np

In [7]:
# 1.
first = np.ones(8)
first


array([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# 2. 
sec = np.ones((4,5))
sec

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# 3. 
th = np.ones((3,3))
th

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# 4. 
first = first * 10
first

array([10., 10., 10., 10., 10., 10., 10., 10.])

In [17]:
# 5. 
an = np.ones(8)
an = an + first
an

array([11., 11., 11., 11., 11., 11., 11., 11.])

In [18]:
# 6. 
f = np.ones(8)
an = an * f
an

array([11., 11., 11., 11., 11., 11., 11., 11.])

In [ ]:
# 7. 
# every ones array idefaultlt float 


In [26]:
# 8.
an = an.astype(int)
an.dtype

dtype('int64')

In [27]:
# 9. 
first = first - 1
first

array([9., 9., 9., 9., 9., 9., 9., 9.])

In [29]:
# 10. 
a = np.ones(6)
a.reshape(2,3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
# 11.
n_neurons = 10
n = np.ones((1,n_neurons))
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
# 12.
print(first.itemsize)
print(first.dtype)

8
float64


In [38]:
# 13.
n = n -1 
n

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# 14. 
ab = np.ones(5)
ano = np.array([-1,0.5,-5.5,4,0])
result = ((ab > ano))   # mask operation
result


array([ True,  True,  True, False,  True])

In [ ]:
# 15. Why "Ones" are Useful in Normalization
# Normalization is the process of scaling data to a specific range (usually 0 to 1).
#  The value 1 (and arrays of ones) serves several critical roles in this process:

# A. The "Unity" Benchmark
# In Min-Max scaling, the goal is to make the maximum value in your dataset equal to 1.

# Formula: x 
# new
# ​
#  = 
# max−min
# x−min
# ​
# When x=max, the result is exactly 1. Having an array of ones gives you a target "ceiling"
# to compare your data against to see how close each point is to the maximum.

# B. Broadcast Multipliers (Equal Weighting)
# When you start a calculation, you often want to treat all features equally. 
# A ones array acts as a "Neutral Weight Vector."

# If you multiply your data by an array of ones, nothing changes.

# This allows you to build a system where you start with 100% weight for everything and
#  then use boolean conditions to "mask out" (multiply by 0) or "dampen" (multiply by 0.5) specific parts of the data.

# C. Handling Division by Zero
# In some normalization formulas, you might add a very small constant (like 1e−8)
# to a ones array to ensure that when you divide data, you never encounter a "Divide by Zero" error.
# The ones array provides the structure, and the small value provides the safety.

# D. Probability Distributions
# In machine learning (like Softmax), we normalize outputs so that they sum up to 1.
# We often compare our calculated sums against a "ones" reference to check if the data
# has been correctly converted into a valid probability distribution (where 100% = 1).

# Would you like to see a code example of Min-Max normalization using a ones array as a scaling factor?