Questions : 

1. Create a 1D array of 5 zeros.

2. Create a 2D array of shape (3, 4) filled with zeros.

3. Create a 3D array of zeros with shape (2, 2, 3).

4. Create a zero matrix for storing student marks (5 students, 3 subjects).

5. Create a zero array and change only one value.

6. Create a zero array of floats.

7. Create a zero array of integers.

8. Create a zero array and check its default dtype.

9. Use zeros to initialize a results table.

10. Create a square zero matrix of size 6.

11. Create a zero array and reshape it.

12. Create a zero array and add another array to it.

13. Create a zero array and use it as a mask.

14. Create a zero array and assign values using indexing.

15. Why is zeros() preferred over empty lists for initialization?

In [1]:
import numpy as np

In [3]:
# 1. 
zero1 = np.zeros(5)
zero1

array([0., 0., 0., 0., 0.])

In [32]:
# 2. 
zero2 = np.zeros((3,4))

zero2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# 3.
zero3 = np.zeros((2,2,3))
zero3

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# 4.
zero4 = np.zeros((5,3))   # row for student and column for subjects
zero4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# 5. 
zero2[0,0] = 5
zero2[0,1] = 10
zero2[0,2] = 15
zero2[0,3] = 20

zero2

array([[ 5., 10., 15., 20.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [37]:
# 6. 
# 7. 
zero5 = np.zeros((3,3))
zero5 = zero5.astype(int)
print(zero5.dtype)
zero6 = np.zeros((3,3))
zero6 = zero6.astype(float)
print(zero6.dtype)

int64
float64


In [ ]:
# 8.
er = np.zeros(5)
print(zer.dtype)

float64


In [ ]:
# 9. 10.
result = np.zeros((5,3))
result[0] = [87,85,94]
result[1] = [67,34,56]
result[2]  = [65,75,79]
result[3] = [65,27,80]
result[4] = [78,96,34]
print(result)
zer1 = np.zeros((6,6))
zer1


[[87. 85. 94.]
 [67. 34. 56.]
 [65. 75. 79.]
 [65. 27. 80.]
 [78. 96. 34.]]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [48]:
# 11.
z = np.zeros(6)
z = z.reshape(2,3)
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# 12.
z = np.zeros(6)
ar = np.array([1,2,3,4,5,6])
z = z + ar
z

array([1., 2., 3., 4., 5., 6.])

In [ ]:
# 13.Why is zeros() preferred over empty lists for initialization?
# np.zeros() is preferred because it pre-allocates a contiguous block of memory, enabling significantly faster performance and 
# multi-dimensional organization compared to the dynamic resizing and overhead of Python lists.