Practice of array, zeros, ones, arange, linspace, eye methods

Questions : 

1. Convert a Python list [10, 20, 30, 40] into a NumPy array.

2. Convert a tuple (5, 10, 15) into an array.

3. Convert a list of lists into a 2D array.

4. Create an array from mixed integers and floats and observe dtype.

5. Create a 3×3 array using nested lists.

6. Convert a list containing strings and numbers — what happens?

7. Convert a list [1, 2, 3] and multiply it by 2 using NumPy.

8. Convert a list and check its .ndim.

9. Convert a list and print its .shape.

10. Convert a list of lists with unequal length — what error do you get?

11. Convert a Pandas Series into a NumPy array.

12. Convert a Python range object into an array.

13. Convert a list and force dtype to float.

14. Convert a list and force dtype to int.

15. Convert boolean values into a NumPy array.

16. Create a NumPy array from [True, False, True].

17. Convert a list of lists and flatten it.

18. Convert a list and check memory type.

19. Convert nested tuples into a NumPy array.

20. Create an array and check if it is mutable.

In [2]:
import numpy as np
import pandas as pd


In [4]:
# 1. 
pylist = [1,2,3,4,5]
npArr = np.array(pylist)
npArr

array([1, 2, 3, 4, 5])

In [5]:
# 2. convert tuple into array
pyTuple = (5,10,15,20)
npArr2 = np.array(pyTuple)
npArr2


array([ 5, 10, 15, 20])

In [6]:
# 3.Convert a list of lists into a 2D array.
list2d = [[1,2,3],[4,5,6,],[7,8,9]]
npArr3 = np.array(list2d)
npArr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# 4.Create an array from mixed integers and floats and observe dtype.
mixArr = np.array([1,2,3,4.5,6.7,8.8])
print(mixArr.dtype)
mixArr

array([1. , 2. , 3. , 4.5, 6.7, 8.8])

In [11]:
# 5.Create a 3×3 array using nested lists.
# already done in 3rd question


In [13]:
# 6.Convert a list containing strings and numbers — what happens?
list = ['Samir','chetna',6,7]
strArr = np.array(list)
strArr
# In NumPy, dtype='<U21' indicates a Unicode string data type that can hold strings up to 21 characters long.

array(['Samir', 'chetna', '6', '7'], dtype='<U21')

In [20]:
# 7.Convert a list [1, 2, 3] and multiply it by 2 using NumPy.
lst = [1,2,3]
lstArr = np.array(lst)
lstArr = lstArr * 2
print(lstArr)

[2 4 6]


In [ ]:
# 8.Convert a list and check its .ndim.
lstArr.ndim    # number of dimensions

1

In [24]:
# 9.
print(npArr3)
npArr3.shape


[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [ ]:
#10.
newArr = np.array([[1,2,3],[11,22,33,44,55]])
# inhomogeneous shape error

In [7]:
# 11.
s = pd.Series([1,2,3,4,5,6,7,8,9])
seriesArr = np.array(s)
seriesArr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#12.
myrange= range(11)
listOFRange= list(myrange)
print(listOFRange)
rangeARR = np.array(listOFRange)
rangeARR


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#13.
intList = [23,51,26,1,4,61,71]
floatARR = np.array(intList)
floatARR = floatARR.astype(float)
# OR
floatARR = np.array(intList,dtype=float)
print(floatARR)
print(floatARR.dtype)



[23. 51. 26.  1.  4. 61. 71.]
float64


In [ ]:
# 14.
lst1 = [12.1,42.55,91.99,78.12,34.90]
IntArr = np.array(lst1,dtype=int)
(IntArr)
print(IntArr.dtype)

int64


In [ ]:
# 15. 
# 16.
bool1 = True
bool2 = False
lst2 = [bool1,bool2,True,False,True,True]
lst2
boolArr = np.array(lst2)
boolArr


array([ True, False,  True, False,  True,  True])

In [ ]:
# 17.
lsst = [[34,154,35],[67,2,51],[90,12,45]]
ar = np.array(lsst)
# ar = ar.flatten()   creates a complete new array and copy element
ar = ar.ravel()    # View (usually). It shares memory with the original array.
ar


array([ 34, 154,  35,  67,   2,  51,  90,  12,  45])

In [ ]:
# 18.
# there are total 3 technique to check the memory type (copy or view)
# a. base attribute
# b. flags object
# c. shares_memory() method 
anArr = np.arange(10)
anArr2 = anArr[::2]
print(anArr)
print(anArr2)
print(anArr2.base) 
# base attribute is use to check if the array is view or copy. if (array.base) value is none then it is copy
# else it will return the base array or the original full array


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# use of flags 
print(anArr.flags.owndata)      # return true/false   return true if have its own memory
print(anArr.flags.writeable)      # return true/false   return true if you can change the value          



True
True
False


In [56]:
# use of shares_memory
np.shares_memory(anArr,anArr2)

True

In [58]:
# 19. 
tup = ((1,2,3),(4,5,6))
arr = np.array(tup)
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 20. 
arr.flags.writeable  # if True then mutable 

True