1. Compute row-wise sum of a 2D array.
2. Compute column-wise sum of a 2D array.
3. Explain why axis=0 works column-wise.
4. Explain why axis=1 works row-wise.
5. Compute row-wise mean.
6. Compute column-wise mean.
7. Compute row-wise standard deviation.
8. Compute column-wise min.
9. Compute max per column.
10. Predict shape after applying sum(axis=0).
11. Predict shape after applying sum(axis=1).
12. Apply reduction on 3D array along axis=0.
13. Apply reduction on 3D array along axis=1.
14. Apply reduction on 3D array along axis=2.
15. Explain axis using “collapse direction”.
16. Compute row-wise sum and subtract from original.
17. Normalize data using axis.
18. Find column with maximum average.
19. Compute sum along wrong axis — explain error.
20. Chain reshape + axis.
21. Use axis after slicing.
22. Compute per-row min and max.
23. Compute per-column range (max − min).
24. Predict output without running code.
25. Compare keepdims=True vs default.
26. Explain broadcasting after axis reduction.
27. Why axis mistakes cause silent bugs?
28. Axis usage in Pandas vs NumPy.
29. Convert axis logic into plain English.
30. One real-world dataset axis example.

In [2]:
import numpy as np

In [3]:
1.
2.
arr = np.array([[45,23,74],
               [95,28,21],
               [72,82,62]])
s = arr.sum(axis=1)
print(f"Row wise sum of matrix is : {s}")
s = arr.sum(axis=0)
print(f"Column wise sum of matrix is : {s}")

Row wise sum of matrix is : [142 144 216]
Column wise sum of matrix is : [212 133 157]


In [4]:
5.
6.
m = arr.mean(axis=1).round(2)
print(f"Row wise mean of matrix is : {m}")
m = arr.mean(axis=0).round(2)
print(f"Column wise mean of matrix is : {m}")

7.
sd = arr.std(axis=1).round(2)
print(f'Row-wise standered deviation is : {sd}')

8.
minn = arr.min(axis=0)
print(f"column wise minimum : {minn}")

9.
maxx = arr.max(axis=0)
print(f"column wise maximum : {maxx}")


Row wise mean of matrix is : [47.33 48.   72.  ]
Column wise mean of matrix is : [70.67 44.33 52.33]
Row-wise standered deviation is : [20.89 33.36  8.16]
column wise minimum : [45 23 21]
column wise maximum : [95 82 74]


In [5]:
10.
11.
add = arr.sum(axis=1)
print(add)
add = arr.sum(axis=0)
print(add)


[142 144 216]
[212 133 157]


In [6]:
12.
arr3d = np.array([[[1,2,3],[43,25,61],[86,14,67]],[[54,71,45],[65,43,13],[87,34,70]]])
print(arr3d)
print()
add = arr3d.sum(axis=0)
print(add)
print()
13.
add = arr3d.sum(axis=1)
print(add)
print()
14.
add = arr3d.sum(axis=2)
print(add)

[[[ 1  2  3]
  [43 25 61]
  [86 14 67]]

 [[54 71 45]
  [65 43 13]
  [87 34 70]]]

[[ 55  73  48]
 [108  68  74]
 [173  48 137]]

[[130  41 131]
 [206 148 128]]

[[  6 129 167]
 [170 121 191]]


In the world of data science and programming (especially with libraries like **NumPy** or **Pandas**), thinking of an axis as the **"collapse direction"** is actually the "secret sauce" to finally making it click.

When you perform an operation like `.sum(axis=n)`, you aren't just selecting a dimension; you are telling the computer which dimension should **disappear**.

---

## The "Collapse" Mental Model

Imagine a 3D accordion or a stack of paper. When you "collapse" an axis, you are squashing all the data along that specific direction into a single point (or a flatter surface).

### Axis 0: The Vertical Collapse

In a 2D array (a table), **Axis 0** refers to the rows.

* **The Action:** Imagine placing a heavy weight on top of the table, crushing it downward.
* **The Result:** All the rows "collapse" into one single row. You are left with a sum (or average) for each column.

### Axis 1: The Horizontal Collapse

**Axis 1** refers to the columns.

* **The Action:** Imagine a trash compactor pushing in from the right side toward the left.
* **The Result:** All the columns "collapse" into one single column. You are left with a sum (or average) for each row.

---

## Comparison Table

| Operation | Axis | Movement | Intuition |
| --- | --- | --- | --- |
| **Sum(axis=0)** | Rows | Vertical (Top to Bottom) | "Squash the rows into one floor." |
| **Sum(axis=1)** | Columns | Horizontal (Left to Right) | "Squash the columns into one wall." |

---

## Why this matters

Most people get confused because they think "Axis 0 means rows, so I should get row totals." **It’s the opposite.** If you collapse the "row-ness" of the data (Axis 0), you are left with the column-wise totals. If you collapse the "column-ness" (Axis 1), you are left with the row-wise totals.

> **Pro Tip:** If you have a 3D array (like a stack of images), **Axis 0** collapses the entire stack into one flat image. You're effectively "squashing" the depth.

Would you like to see a code example using a small NumPy array to see how these numbers actually "squash" in real-time?

In [7]:
16.
add = arr.sum(axis=1)
print(add)
print()
result = add - arr 
print(result)

[142 144 216]

[[ 97 121 142]
 [ 47 116 195]
 [ 70  62 154]]


In [8]:
17.
# Normalize data using axis?



17.0

In [9]:
18.
arr1 = np.array([[43,62,73],[53,43,64],[12,45,78]])
max_avg = arr1.mean(axis=0).max()
print(f"maximum average in columns is :{max_avg}")


maximum average in columns is :71.66666666666667


In [10]:
21.
sliced = arr1[0:2,0:2]
print(sliced)
s1,s2 = sliced.sum(axis=1),sliced.sum(axis=0)
print(s1,s2)

[[43 62]
 [53 43]]
[105  96] [ 96 105]


In [11]:
22.
print(arr1)
row_min, row_max = arr1.min(axis=1), arr1.max(axis=1)
print(f"minimum in each row is : {row_min}",f"maximum in each row is : {row_max}",sep='\n')
print()
23.
col_min, col_max = arr1.min(axis=0), arr1.max(axis=0)
print(f"minimum in each row is : {col_min}",f"maximum in each row is : {col_max}",sep='\n')

[[43 62 73]
 [53 43 64]
 [12 45 78]]
minimum in each row is : [43 43 12]
maximum in each row is : [73 64 78]

minimum in each row is : [12 43 64]
maximum in each row is : [53 62 78]


In [ ]:
25.
sum_arr1 = arr1.sum(axis=1)
print(sum_arr1)
print(sum_arr1.shape)
# shape after using keepdims
print()
sum_arr1 = arr1.sum(axis=1,keepdims=True)
print(sum_arr1)
print(sum_arr1.shape)

# When keepdims is set to True, the axes that are reduced (collapsed) in the operation are retained in the result array as dimensions with a size of one. 


[178 160 135]
(3,)

[[178]
 [160]
 [135]]
(3, 1)


## 26.  Explain broadcasting after axis reduction?

Broadcasting after axis reduction refers to how NumPy (and similar libraries like TensorFlow or PyTorch) handles array shapes during operations like sum, mean, or max along a specific axis, preserving dimensions for compatibility with other arrays.

## Core Concept
Axis reduction operations (e.g., `np.sum(array, axis=0)`) collapse a specified dimension, reducing the array's rank. Broadcasting then automatically expands the reduced result to match shapes in element-wise operations, following rules: pad shapes with 1s on the left, align from the right, and stretch dimensions of size 1. [tutorialspoint](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)

## Example in NumPy
Consider a 3x4 array reduced along axis=0 (columns):
```
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9,10,11,12]])
reduced = np.sum(arr, axis=0)  # Shape: (4,) → sums to [15,18,21,24]
```
Now multiply by a row vector of shape (1,4): `reduced[None, :] * row_vector`. Broadcasting pads `(4,)` to `(1,4)`, enabling seamless multiplication without explicit reshaping. [tutorialspoint](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)

## Why It Matters
This prevents shape mismatches in chains like `np.mean(data, axis=0)[:, None] * weights`, common in data processing or ML. The reduced axis becomes size 1 or is virtually expanded, avoiding errors in vectorized code. [openxla](https://openxla.org/xla/broadcasting)



## 27. Why axis mistakes cause silent bugs?

The most dangerous part of axis errors is that they often **don't trigger an error message.** Instead, they produce "junk data" that looks valid.

* **Broadcast Compatibility:** If you have a square matrix (e.g., ), performing an operation on `axis=0` vs `axis=1` results in the same shape . Python will happily broadcast either one back against the original matrix, even if you calculated the wrong one.
* **Semantic Nonsense:** You might intend to subtract the "Average Price per Product" but accidentally subtract the "Average Price per Store." The math "works," but your insights are now fundamentally flawed.
* **Default Behavior:** Many functions default to `axis=0`. If you forget to specify, the code runs, but it might be aggregating across rows when you meant to aggregate across columns.

---

## 28. Axis usage in Pandas vs. NumPy

While they share the same underlying logic, their "personalities" differ slightly in how they handle labels.

| Feature | NumPy | Pandas |
| --- | --- | --- |
| **Primary Focus** | Integer positions (). | Labels (`index`, `columns`). |
| **Terminology** | Dimensions/Axes. | Rows/Columns. |
| **Default Axis** | Often `None` (flattens the whole array). | Usually `0` (operates down the index). |
| **Flexibility** | Strictly numerical. | You can use `axis='rows'` or `axis='columns'`. |

---

## 29. Convert axis logic into plain English

The "0 and 1" convention is notoriously counter-intuitive. Here is the best way to translate it into your internal monologue:

* **Axis 0 (The "Down" Axis):**
* *Logic:* Collapses the rows.
* *Plain English:* "Give me a result for **each column**."
* *Action:* Moving vertically down the stack.


* **Axis 1 (The "Across" Axis):**
* *Logic:* Collapses the columns.
* *Plain English:* "Give me a result for **each row**."
* *Action:* Moving horizontally across the record.



---

## 30. One real-world dataset axis example

Imagine a **Weather Station Dataset** where:

* **Rows** = Days of the year (365).
* **Columns** = Different cities (New York, London, Tokyo).

**The Axis Decisions:**

1. **`df.mean(axis=0)`:** You are collapsing the "Days" dimension. You get the **average temperature for each city** over the whole year.
2. **`df.mean(axis=1)`:** You are collapsing the "Cities" dimension. You get the **global average temperature for each day**.

If you mix these up, you might report the average temperature of Tokyo as the average temperature of the entire world on January 1st!

---

Would you like me to generate a small sample DataFrame so we can practice applying these axes to real numbers?
