In [2]:
import numpy as np
# Scaler operation
arr = np.array([1,2,3,4,5])
arr + 1  # add 1 in every element 

array([2, 3, 4, 5, 6])

In [3]:
# we can perform all arithmetic operation like this on array
arr**2

array([ 1,  4,  9, 16, 25])

In [4]:
arr -1

array([0, 1, 2, 3, 4])

In [ ]:
b = np.ones(5) + 1  # [2,2,2,2,2]
arr- b 


array([-1.,  0.,  1.,  2.,  3.])

| Feature           | `np.dot(a, b)`        | `a * b`                       |
| ----------------- | --------------------- | ----------------------------- |
| Type of operation | Linear algebra        | Element-wise                  |
| Shape rules       | Matrix rules apply    | Same shape (or broadcastable) |
| Result meaning    | Sum of products       | Direct multiplication         |
| Used in           | ML, DL, math, physics | Data scaling, masking         |

Element-wise means:
👉 Operate on each position independently.

dot product
a = [1, 2, 3]
b = [4, 5, 6]

a · b = (1×4) + (2×5) + (3×6) = 32




element wise 
a = [1, 2, 3]
b = [4, 5, 6]

a * b   →   [1*4, 2*5, 3*6]



In [16]:
# matrix multiplication
x = np.diag([4,5,6,7,8])
print(x * 2)
print()
print(x.dot(x))

[[ 8  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0 14  0]
 [ 0  0  0  0 16]]

[[16  0  0  0  0]
 [ 0 25  0  0  0]
 [ 0  0 36  0  0]
 [ 0  0  0 49  0]
 [ 0  0  0  0 64]]


In [25]:
# relational operation for matrix 

m = np.array([1,7,5,3,9])
n = np.array([1,6,3,78,2])


In [26]:
m == n
# COMPARE EACH VALUE IN WITH THE SAME INDEX 
# SIZE OF BOTH ARRAY MUST BE SAME 

array([ True, False, False, False, False])

In [27]:
m > n


array([False,  True,  True, False,  True])

In [30]:
d = np.array([1,2,3,4])
e = np.array([1,2,3,4])
np.array_equal(d,e)
# array_equal method compare the each index, if every element is same then return true
# and if any one element is not same then return false 

True

In [ ]:
# sum method give sum of all element 
print(d.sum())

ar = np.array([[1,2,3],[4,5,6]])
print(ar.sum(axis=0))  # sum of columns 
print(ar.sum(axis=1))   # sum of rows 

10
[5 7 9]
[ 6 15]


In [35]:
# other methods
print("for minimum element in array :",ar.min())
print("for maximum element in array :",ar.max())
print()
print("index of minimum element : ", ar.argmin())
print("index of maximum element : ", ar.argmax())



for minimum element in array : 1
for maximum element in array : 6

index of minimum element :  0
index of maximum element :  5


In [ ]:
# logical operation 

print(np.all([True,True,False])) # if all are true then true 
print(np.any([True,True,False])) # if all are false then false 

False
True


In [6]:
# use of all method 
a = np.array([1,2,5,2,6])
b = np.array([9,74,33,8,22])
c = np.array([100,200,300,400,500])

((a < b) & (b < c)).all()  # mean if condition is true for all then its true else false 

np.True_

**Statistics** 

In [15]:
z = np.array([1,2,3,5,6,7,8,9,10,11,12,13,14,15,16])
print("mean of the array is ",np.median(z))
print('median of the array is ',z.mean())

mean of the array is  9.0
median of the array is  8.8


77.4e^3 = 77.4 * 10^3 


In [16]:
# loading data using numpy 
# data = np.loadtxt("file name /file path")

**Broadcasting**

basic operation on numpy arrays are elemeentwise (possible if size of arrays are same)

its possible to do operations of arrays with different shape or size if numpy can transform these arrays
into same size, this method is called broadcasting

Example:
A (3×3 array)        B (1×3 array)

A =                 B =
┌───┬───┬───┐       ┌───┬───┬───┐
│ 1 │ 2 │ 3 │       │10 │20 │30 │
├───┼───┼───┤
│ 4 │ 5 │ 6 │
├───┼───┼───┤
│ 7 │ 8 │ 9 │
└───┴───┴───┘


Broadcasting Process
────────────────────

B is stretched (NOT copied in memory):

┌───┬───┬───┐
│10 │20 │30 │
├───┼───┼───┤
│10 │20 │30 │
├───┼───┼───┤
│10 │20 │30 │
└───┴───┴───┘


Element-wise Operation (A + B)
─────────────────────────────

┌───┬───┬───┐
│11 │22 │33 │
├───┼───┼───┤
│14 │25 │36 │
├───┼───┼───┤
│17 │28 │39 │
└───┴───┴───┘


In [36]:
# tile method is use for broadcasting 
arry = np.array([1,2,3,4])
arry = np.tile(arry,(5,1))  # (strech row , strech column)
print(arry)


[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [37]:
# we can transpose the matrix (row become column and column become row)
arry.T

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [38]:
arry2 = np.array([4,5,6,7])

In [39]:
arry+arry2   # broadcasting happen internally and broadcasting happen according to column

array([[ 5,  7,  9, 11],
       [ 5,  7,  9, 11],
       [ 5,  7,  9, 11],
       [ 5,  7,  9, 11],
       [ 5,  7,  9, 11]])

In [3]:
# first = np.array([[1,2,4],[]])   we can't create a single column array like this 
first = np.arange(0,50,10)
first = first[:,np.newaxis]  # creating 2d array 
print(first)
print(first.shape)

[[ 0]
 [10]
 [20]
 [30]
 [40]]
(5, 1)


In [9]:
# reshape method 
for_reshape = np.array([1,2,3,4,5,6])
for_reshape = for_reshape.reshape(6,1)
print("converting simple array into a matrix using reshapce method")
print(for_reshape)

# changing again into a normal array using ravel method 
for_reshape = for_reshape.ravel()
print("Converting matrix into simple array using ravel method")
print(for_reshape)


converting simple array into a matrix using reshapce method
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Converting matrix into simple array using ravel method
[1 2 3 4 5 6]


In [11]:
a = np.array([1,2,3])
b = np.array([1,2,3])
a+b

array([2, 4, 6])