Questions : 
1. Compute the sum of all elements in a 1D array.
👉 Tests basic reduction.

2. Find the mean of a 1D array with floats.

3. Find the minimum value in a 2D array.

4. Find the maximum value in a matrix.

5. Compute standard deviation of a dataset.

6. Explain difference between sum() and Python sum().

7. Compute sum of boolean array — explain output.

8. Find mean after flattening a 2D array.

9. Compute min and max in one line.

10. Use reduction functions after slicing.

11. Compute sum of an empty array — what happens?

12. Apply reduction on integer array and check dtype.

13. Why does std() return float even for int arrays?

14. Compare np.mean() vs arr.mean().

15. Compute reduction after boolean masking.

16. Compute sum of masked values only.

17. Apply reduction to output of reshape().

18. Predict result without running code.

19. Use reductions to validate data consistency.

20. Explain real-life use of mean, std.

In NumPy, a **reduction function** is an operation that removes one or more dimensions from an array by performing a calculation along a specific axis.

While a standard Python reduction (like `functools.reduce`) typically results in a single scalar value, NumPy is much more powerful because it allows you to reduce across **rows**, **columns**, or the **entire multi-dimensional structure**.

---

## 1. How NumPy Reductions Work

Most NumPy reduction functions follow a common signature: `np.function(array, axis=None)`.

* **`axis=None` (Default):** Reduces the entire array into a single number.
* **`axis=0`:** Reduces down the **rows** (calculates a result for each column).
* **`axis=1`:** Reduces across the **columns** (calculates a result for each row).

### Code Example:

```python
import numpy as np

data = np.array([[1, 2, 3], 
                 [4, 5, 6]])

# Total reduction (everything)
print(np.sum(data))          # Output: 21

# Column-wise reduction (collapse rows)
print(np.sum(data, axis=0))  # Output: [5, 7, 9]

# Row-wise reduction (collapse columns)
print(np.sum(data, axis=1))  # Output: [6, 15]

```

---

## 2. Common Reduction Functions

NumPy provides a wide suite of these functions, all optimized in C for extreme speed.

| Function | Description |
| --- | --- |
| `np.sum()` | Adds all elements. |
| `np.prod()` | Multiplies all elements. |
| `np.mean()` | Calculates the arithmetic mean. |
| `np.std()` | Calculates the standard deviation. |
| `np.all()` | Logical AND (returns True if **all** elements are True). |
| `np.any()` | Logical OR (returns True if **any** element is True). |
| `np.argmin()` | Returns the **index** of the minimum value. |

---



In [2]:
import numpy as np

In [3]:
1.
arr = np.array([1,2,3,4,5])
sum_of_elements = arr.sum()
print(f"Sum of all element in the array is : {sum_of_elements}")

2. 
mean_of_arr = arr.mean()
print(f"mean of the array's element is : {mean_of_arr}")

Sum of all element in the array is : 15
mean of the array's element is : 3.0


In [11]:
3. 
arr_2d = np.array([[56,48,28],
                   [92,817,12],
                   [73,27,14]])

minimum = arr_2d.min()
print(f"minimum element in the array is : {minimum}")
4.

maximum = arr_2d.max()
print(f"maximum element in the array is : {maximum}")

9.
mm,mx = arr_2d.min(), arr_2d.max()
print(mm,mx)

minimum element in the array is : 12
maximum element in the array is : 817
12 817


In [26]:
5. 
# Set seed for consistency
np.random.seed(10)

# Metrics: [Units Sold, Customer Count, Returns]
# 5 Stores, 12 Months, 3 Metrics
sales_data = np.random.randint(low=[100, 50, 0], 
                               high=[500, 200, 20], 
                               size=( 12, 3))

print("Shape:", sales_data.shape)
print(sales_data)
# Example: sales_data[0, 0] -> [Units, Customers, Returns] for Store 0 in Jan
col = [0]
standered_deviation = sales_data[:,col].mean(axis=0)
print(f"mean is {standered_deviation}")
standered_deviation = sales_data[:,col].std(axis=0)
print(f"std is {standered_deviation}")



Shape: (12, 3)
[[365 175   4]
 [115 114  17]
 [223 163   8]
 [173  50  10]
 [140 165  16]
 [456 189  11]
 [222 112   1]
 [300 150  14]
 [277 104  13]
 [113 176  13]
 [448 136  12]
 [421  81   4]]
mean is [271.08333333]
std is [121.97572049]


# **6. Explain difference between sum() and Python sum().**
While they share the same name and goal, `numpy.sum()` and Python’s built-in `sum()` are worlds apart when it comes to how they handle data and memory.

---

## 1. Scope and Input

* **Python `sum()**`: Designed for **general-purpose iteration**. It works on any iterable (lists, tuples, dictionaries) and adds the elements one by one. It is optimized for standard Python objects.
* **NumPy `sum()**`: Specifically engineered for **numerical arrays**. It is aware of array dimensions (axes) and is written in C for massive performance gains.

---

## 2. Dimensionality (The "Axis" Power)

This is the biggest functional difference. Python's `sum()` has no concept of rows or columns; it just flattens everything it can.

* **Python `sum()**`: If you pass a 2D list to Python's `sum()`, it will likely throw an error because it tries to add a list to an integer.
* **NumPy `sum()**`: Can sum across specific directions using the `axis` parameter.

```python
import numpy as np

arr = np.array([[1, 2], [3, 4]])

# NumPy can sum columns
print(np.sum(arr, axis=0)) # Output: [4, 6]

# Python sum would fail on the 2D array directly
# sum(arr) -> TypeError

```

---

## 3. Performance (Speed)

Because NumPy uses **vectorization**, it performs the addition in compiled C code, bypassing the overhead of the Python interpreter for every single element.

| Data Size | Python `sum()` | NumPy `sum()` |
| --- | --- | --- |
| 1,000 items | Fast | Very Fast |
| 1,000,000 items | Slow (Seconds) | Instant (Milliseconds) |

> **The Golden Rule:** Never use Python's built-in `sum()` on a NumPy array. It is significantly slower because it has to "extract" each number from the NumPy format back into a Python object before adding it.

---

## 4. Handling Missing Data

* **Python `sum()**`: If there is a `None` or a `NaN` (Not a Number), it will usually crash.
* **NumPy `sum()**`: If there is a `NaN`, the result will be `NaN`. However, NumPy also provides `np.nansum()`, which ignores missing values and sums the rest.

---

### Summary Comparison Table

| Feature | Python `sum(iterable)` | `numpy.sum(array)` |
| --- | --- | --- |
| **Data Type** | Lists, Tuples, Sets | NumPy Arrays |
| **Algorithm** | Sequential (Looping) | Vectorized (Parallel-like) |
| **Multi-dimensional** | No | Yes (via `axis`) |
| **Speed** | Standard | Blazing Fast |

---




In [8]:
7. 
boolean_arr = np.array([True,False,True,False,True,True,False])  # True = 1 False = 0 
add = boolean_arr.sum()
print(f"Sum of boolean array is : {add}")

Sum of boolean array is : 4


In [10]:
8.
arr = np.array([[1,2,3],
                [4,5,6],
                [23,52,62]])
arr = arr.ravel()
meen = arr.mean()
print(f"mean of the 2d array after falttening is : {meen}")

mean of the 2d array after falttening is : 17.555555555555557


In [23]:
10.

ar2 = np.array([[1,2,3],
                [4,5,6],
                [23,52,62]])
sliced = ar2[1]
sum_slice = sum(sliced)
print(f"Sum of sliced array is : {sum_slice}")

12.
print(sum_slice.dtype)


Sum of sliced array is : 15
int64


In [21]:
11.

empty = np.array([])
sum_em = empty.sum()
print(f"sum of the empty array is : {sum_em}")

sum of the empty array is : 0.0


**13.Why does std() return float even for int arrays?**

Standard deviation returns a float because the division (for the mean) and the square root (for the final value) rarely result in whole numbers, and using integers would cause significant loss of precision.


In [28]:
14.
Arr = np.array([34,52,76,52,5,72,67,85,68,79,89])

first_mean = np.mean(Arr)
second_mean = Arr.mean()

print(f"first mean is : {first_mean}")
print(f"second mean is : {second_mean}")

first mean is : 61.72727272727273
second mean is : 61.72727272727273


In [35]:
15.
mask = Arr > 60

print(Arr[mask])
print(mask)
print(np.sum(mask))

16.
print(f"sum of the masked values is : {Arr[mask].sum()}")

[76 72 67 85 68 79 89]
[False False  True False False  True  True  True  True  True  True]
7
sum of the masked values is : 536


In [ ]:
# 16, 17, 18 , 19  20 can be done easily 