In [2]:
import numpy as np


In [3]:
print("hello world we are going to learn numpy ")

hello world we are going to learn numpy 


In [4]:
# creating array method 
arr = np.array([1,2,3,4,5])
print(arr)
# another method 
# ARANGE method  = arange() is NumPy’s numerical version of range(), 
# but returns an actual array stored in memory.
# syntax = np.arange(start, stop, step, dtype)
print(np.arange(10))

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
list = range(1000)
%timeit [ 1**2 for i in list]


13.8 μs ± 571 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
list2 = np.arange(1000)
%timeit [list2**2]

914 ns ± 248 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Here we see that list in python takes a lot of time and the numpy array do the same task in almost half time

In [7]:
list2.ndim   # attribute use to check the dimensions of the array 

1

In [8]:
list2.shape # it will give the shape (matrix) of an array

(1000,)

In [9]:
# creating 2 dimensional array 
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2.shape)    # output format = (row, column)
print(arr2.ndim)


(2, 4)
2


In [10]:
len(arr2)

2

In [11]:
a1 = [1,2,4]
a2 = [4,5,6]
new_arr = np.array([a1,a2])
print (new_arr)
print(len(new_arr)) #give only rows 
print(new_arr.shape)  #give rows and column 

[[1 2 4]
 [4 5 6]]
2
(2, 3)


In [12]:
# 3-dimensional array 
# we have to mentain the shape of meatrix otherwise 
# it will through an error
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
print(array_3d.shape)
print(array_3d.ndim)
print(len(array_3d))


(2, 2, 3)
3
2


In [14]:
# 1-d array = vector
# 2-d array = matrix
# n-d array = tensor

In [15]:
# linspace method : numpy.linspace() creates a NumPy array of numbers that are evenly spaced between
# two values, based on a fixed count of elements, not a step size.
# syntax = numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# step calculation : step = (stop − start) / (num − 1)   (if endpoint=True)
# endpoint--->	Whether to include stop
# retstep--->	Whether to return the step size

In [16]:
linspace = np.linspace(0,1,5,endpoint=False,retstep=True)
print(linspace)

(array([0. , 0.2, 0.4, 0.6, 0.8]), np.float64(0.2))


In [17]:
one_matrx = np.ones((3,2)) # take rows and column and print 1 at everywhere (2-dimensional array)
print(one_matrx)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
# zeroes
sero = np.zeros((2,3))
print(sero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# eye method - diagnol is 1 and remaining are zero
first = np.eye(2,3)
second = np.eye(4)
print(first)
print(second)

[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
# diag method = we can give value to diagnol and remaining element will we zero 
diagnol = np.diag([1,2,3,4,5])
print(diagnol)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [21]:
# we can change any value where zero occur by this 
diagnol[1,2] = 10   # first index = row , second index is column 
diagnol[0,2] = 15
diagnol

array([[ 1,  0, 15,  0,  0],
       [ 0,  2, 10,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  5]])

In [22]:
# array slicing 
# syntax = array.slice(START-INDEX, END-INDEX,STEPS)

new = np.array([1,433,3,5,2,42,53,44,6,56,75,75,95,92,27,45,746,7])
new[0:10:5]


array([ 1, 42])

In [23]:
# we can also combine assignment and slicing 
new[5:10] = 100  # from 5 to 9 index value will be 100
new

array([  1, 433,   3,   5,   2, 100, 100, 100, 100, 100,  75,  75,  95,
        92,  27,  45, 746,   7])

In [24]:
new

array([  1, 433,   3,   5,   2, 100, 100, 100, 100, 100,  75,  75,  95,
        92,  27,  45, 746,   7])

In [25]:
# reverse of an array
another_new = np.array([56,75,3,23,3,246,46,90])
new[::-1]


array([  7, 746,  45,  27,  92,  95,  75,  75, 100, 100, 100, 100, 100,
         2,   5,   3, 433,   1])

In [26]:
new


array([  1, 433,   3,   5,   2, 100, 100, 100, 100, 100,  75,  75,  95,
        92,  27,  45, 746,   7])

In [27]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y  = x[::2]  # this will allocate elements to new memory location 


In [28]:
np.shares_memory(x,y)
# In NumPy, shared memory means two or more arrays refer to the same underlying block of memory,
# so changing one array can change the other.
# When an array shares memory, it does not create a new copy of data.
# Instead, it creates a view on the same data buffer.
# So:
# ✔ Fast (no extra memory allocation)
# ✔ Memory efficient
# ❌ Risky if you modify data unintentionally



True

In [29]:
# memory shares every time when we slice the array and assing to another variable , real copy doesn't made
# but if we want to create real copy we have to use ".copy()" method 
b = x[::2].copy()  # create another memory 

In [30]:
# BOOLEAN MASK operation : “Work only on elements where the condition is True.”

In [31]:
one_to_twenty = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

mask = (one_to_twenty % 2 == 0)

only_even = one_to_twenty[mask]
only_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
# mask use : jab bhi kisi condition ki help se value assing, extract ya modify krni ho to 
# mask operation ka use krte h 


In [33]:
# create array of random number from a range of give number 

rng = np.random.default_rng()

# For integers
integers = rng.integers(low=0, high=10, size=5)

# For floats in a range
floats = rng.uniform(low=0, high=10, size=5)

print(integers)
print(floats)

[9 8 6 2 0]
[5.02335715 2.18989146 5.51297315 2.54203066 8.22658596]
