Questions : 

1. Create a 1D array of 10 elements and check its shape.
👉 Tests understanding that 1D arrays have shape (n,), not (n,1).

2. Create a 2D array (3 rows, 4 columns) and print its shape.

3. Create a 3D array and identify its ndim.
👉 Tests dimension counting, not size.

4. Convert a nested list into an array and determine ndim.

5. Why does a single list produce ndim = 1?

6. Create an array using arange(12) and reshape it to (3,4).
7. What is the shape before and after?

8. Create a column vector and check its shape.

9. Convert a column vector to a row vector and verify shape change.

10. Create an array and explain the difference between len(arr) and arr.shape.

11. Create an array and predict ndim without running code.

12. Create a scalar NumPy array and check its ndim.

13. Create a 1×5 array and explain why it is still 2D.

14. Create a 5×1 array and compare with 1D array.

15. Given shape (2,3,4), explain what each number represents.

16. Create an array and access its number of dimensions using two methods.

17. Create a 2D array and verify row count using shape.

18. Create a square matrix and confirm rows = columns using shape.

19. Why does reshaping not change total number of elements?

20. Predict error when reshaping into incompatible shape.

21. Explain how shape helps avoid logical bugs in analysis.

In [1]:
import numpy as np


In [23]:
1. 

arr = np.arange(1,11)

print(arr.shape)
arr = arr.reshape(5,2)
print(arr.shape)

2. 
arr2 = np.ones((3,4))
print(arr2)
print(arr2.shape)
arr2[0] =  arr2[0,0] * 4  # broadcasting happening 
arr2[1] =  arr2[1,1] * 5
arr2[2] =  arr2[2,2] * 6
print(arr2)

3. 
print(f"dimension of the array is : {arr2.ndim}")
# ndim method is use to check the dimension of array 

(10,)
(5, 2)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[[4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]]
dimension of the array is : 2


In [25]:
4. 
lst = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
lst_to_arr = np.array(lst)
print(lst_to_arr)
print(f'dimension of coverted list to array is : {lst_to_arr.ndim}')



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
dimension of coverted list to array is : 3


5.  Why does a single list produce ndim = 1?
In NumPy, `ndim` represents the number of **dimensions** (or axes) in an array. Think of it as the number of "layers" of nesting you have to peel back to reach a single number.

Here is why a single list results in `ndim = 1`:

### 1. The Geometry of a List

A single list is a linear collection of elements. In mathematical terms, this is a **vector**.

* To find a specific item in a list, you only need **one coordinate** (the index).
* Because you only need one axis to navigate the data, it is one-dimensional.

### 2. How `ndim` is Calculated

NumPy determines `ndim` by looking at the "depth" of the structure.

* **Scalar (0D):** A single number like `5`. It has no axes.
* **Vector (1D):** A single list like `[1, 2, 3]`. It has one axis (length).
* **Matrix (2D):** A list of lists like `[[1, 2], [3, 4]]`. It has two axes (rows and columns).

---

### Comparison Table

| Structure | Example | `ndim` | Analogy |
| --- | --- | --- | --- |
| **Scalar** | `5` | 0 | A single point |
| **1D Array** | `[1, 2, 3]` | 1 | A straight line |
| **2D Array** | `[[1, 2], [3, 4]]` | 2 | A flat sheet (Table) |
| **3D Array** | `[[[1], [2]], [[3], [4]]]` | 3 | A cube |

### The "Bracket Rule"

A quick trick to identify the `ndim` of a NumPy array just by looking at the code is to count the number of opening square brackets at the very beginning of the array:

* `np.array([1, 2, 3])`  **1** bracket = **1D**
* `np.array([[1, 2]])`  **2** brackets = **2D**

Would you like to see how to use `np.expand_dims` to turn that 1D list into a 2D row or column vector?


In [26]:
6. 
arr3 = np.arange(12)
print(arr3)
print(arr3.shape)
arr3 = arr3.reshape(3,4)
print(arr3)
print(arr3.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
8.
ar = np.arange(10)
ar = ar.reshape(10,1)
print(ar)
print(ar.shape)

9.
ar = ar.ravel()
print(ar)
print(ar.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)
[0 1 2 3 4 5 6 7 8 9]
(10,)


In [ ]:
10.
print(len(arr3))  
# len only work on vector, if array is 2d it only tells the row didn't tell column
print(arr3.shape)
# shape work in matrix OR 2d-array it show both rows and columns, if anything doesn't exist the place will be empty

3
(3, 4)


In [ ]:
12.
# In NumPy, a scalar is an array with zero dimensions (ndim = 0).
ver = 5
a = np.array(ver)
print(f'dimension of array is {a.ndim}')

dimension of array is 0


Here is the breakdown for both structures, along with the explanation of why the dimensions behave the way they do in NumPy.

---

### 1. Create a 1×5 Array

A  array is essentially a **row vector**. Even though it only contains one "line" of data, NumPy considers it 2D.

```python
import numpy as np

arr_1x5 = np.array([[10, 20, 30, 40, 50]])

print(arr_1x5)
print("Shape:", arr_1x5.shape) # Output: (1, 5)
print("Dimensions:", arr_1x5.ndim) # Output: 2

```

**Why is it still 2D?**
It all comes down to the **number of axes**.

* **1D** means you only have one axis (length).
* **2D** means you have two axes (rows AND columns).
* In a  array, you have explicitly told NumPy: "I have 1 row and 5 columns." Because you have defined both a row-axis and a column-axis, it requires two coordinates to locate a value (e.g., `arr[0, 2]`), making it 2D.

---

### 2. Create a 5×1 Array vs. 1D Array

A  array is a **column vector**. While it has the same number of elements as a 1D array, its structural "identity" is different.

#### Comparison Table

| Feature | 1D Array (`arr_1d`) | 5×1 Array (`arr_5x1`) |
| --- | --- | --- |
| **Code** | `np.array([1, 2, 3, 4, 5])` | `np.array([[1], [2], [3], [4], [5]])` |
| **Visual** | `[1, 2, 3, 4, 5]` | `[[1], [2], [3], [4], [5]]` |
| **Shape** | `(5,)` | `(5, 1)` |
| **`ndim`** | **1** | **2** |
| **Analogy** | A single row of passengers on a bus. | A stack of 5 individual trays. |

---

### The "Bracket Rule" Shortcut

The easiest way to tell the dimension without running code is to count the nested square brackets `[` at the start of the array:

* `[ ... ]`  **1 bracket** = 1D (Vector)
* `[[ ... ]]`  **2 brackets** = 2D (Matrix/Row/Column)
* `[[[ ... ]]]`  **3 brackets** = 3D (Tensor/Cube)

### Why does this matter?

Most Machine Learning libraries (like Scikit-learn) expect data in **2D format** (Rows  Columns). If you pass a 1D array `(5,)` instead of a 2D array `(5, 1)`, the code will often throw an error because it's looking for that second "column" dimension!

Would you like to see how to use `.reshape()` to quickly toggle between these three shapes?

In [ ]:
15.
# given shape ---- (2,3,4)
three_d = np.ones((2,3,4))
three_d

# here 2 represent number of matrix inside a matrix 
# 3 represent the number of rown inside each inner matrix
# 4 represent the number of columns inside each inner matrix


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [48]:
16. 
# ist method 
print(three_d.ndim)
print(three_d.shape)  # number of ouput in bracket mean total dimension 

3
(2, 3, 4)


19.
Reshaping does not change the total number of elements because it only changes the **metadata** (the "instructions" on how to read the data), not the **underlying data** itself.

To understand this, you have to look at how NumPy stores information in your computer's memory.

---

### 1. The "Buffer" vs. The "View"

When you create a NumPy array, the actual numbers are stored in a flat, continuous block of memory called a **data buffer**.

* **The Buffer:** A simple, 1D "memory ribbon" containing all your numbers in a row.
* **The Shape:** A set of instructions (metadata) telling NumPy how to "wrap" that ribbon into rows, columns, or layers.

### 2. The Conservation of Elements

Think of a block of 12 LEGO bricks.

* You can arrange them in one long line (**1×12**).
* You can stack them in two rows (**2×6**).
* You can stack them in three rows (**3×4**).

In every scenario, you still have exactly 12 bricks. Reshaping is just the act of rearranging those bricks. If you tried to reshape 12 elements into a  grid (which requires 15 elements), the operation would fail because you don't have enough "bricks" to fill the slots.

### 3. Mathematical Requirement

For a reshape to be valid, the product of the new dimensions must equal the product of the old dimensions.

For example, if you have an array with 12 elements:

* **Valid:** 
* **Valid:** 
* **Invalid:**  (NumPy will throw a `ValueError`)

---

### Summary Table

| Feature | What Happens During Reshape? |
| --- | --- |
| **Data Buffer** | Stays exactly the same. |
| **Memory Address** | Usually stays the same (it creates a "view"). |
| **`ndim` and `shape**` | These are updated to the new values. |
| **Total Size** | **Must** remain constant. |

### Practical Tip: The `-1` Trick

Because the total number of elements is constant, NumPy allows you to use `-1` as a placeholder for **one** of the dimensions. NumPy will do the math for you to ensure the total count stays the same:

```python
import numpy as np
arr = np.arange(12) # 12 elements

# You don't have to calculate that 12 / 3 = 4
new_arr = arr.reshape(3, -1) 
print(new_arr.shape) # Output: (3, 4)

```

Would you like to see how `np.resize()` differs from `np.reshape()`? (Hint: `resize` actually *can* change the number of elements!)