1. Reshape a 1D array of size 12 into a 3×4 matrix.
👉 Tests element conservation.

2. Reshape the same array into 4×3. Compare.

3. Use reshape(-1, 3) and explain what -1 means.

4. Convert a 2D array into 1D using reshape.

5. Reshape a 1D array into a column vector.

6. Reshape a column vector back into 1D.

7. Why does reshape sometimes fail?

8. Predict output shape before reshaping.

9. Reshape a 3D array into 2D.

10. Flatten a matrix using reshape and compare with ravel.

11. Reshape without assigning — does original array change?

12. Explain whether reshape creates copy or view.

13. Use reshape to prepare data for ML model input.

14. Create a matrix and reshape it row-wise.

15. Reshape the same matrix column-wise (conceptual).

16. Explain memory impact of reshape.

17. Why reshape is safer than manually re-creating arrays?

18. Use reshape in combination with arange.

19. Predict reshape error without running code.

20. Explain real-life use of reshape in data analysis.

In [2]:
import numpy as np


In [3]:
1.
2.

arr = np.linspace(1,100,12,dtype=int)
print(arr.shape)
print(arr)
arr = arr.reshape(3,4)
print(arr)
print(arr.shape)

arr = arr.reshape(4,3)
print(arr)
print(arr.shape)

(12,)
[  1  10  19  28  37  46  55  64  73  82  91 100]
[[  1  10  19  28]
 [ 37  46  55  64]
 [ 73  82  91 100]]
(3, 4)
[[  1  10  19]
 [ 28  37  46]
 [ 55  64  73]
 [ 82  91 100]]
(4, 3)


In [5]:
3.
arr2 = np.array([1,2,3])
print(arr2.reshape(-1,3))
print(arr2.reshape(1,3))


[[1 2 3]]
[[1 2 3]]


In this specific case, both lines of code produce the **exact same result**, but they get there using different logic.

Here is the breakdown of why they result in the same shape and what that `-1` actually does.

---

### 1. The Meaning of `-1` in Reshape

Think of `-1` as a **wildcard** or an "Auto-Fill" command. You are telling NumPy:

> "I know I want this many columns (or rows), you do the math and figure out how many of the other dimension I need to fit all my elements."

NumPy looks at the total number of elements in your array and calculates the missing dimension for you.

**The Calculation:**
Your `arr2` has **3 elements**.

* If you call `.reshape(-1, 3)`, NumPy thinks: *Total\,Elements\,(3) \div Requested\,Columns\,(3) = 1\,Row*.
* Therefore, `-1` becomes `1`.

---

### 2. Comparing the Two Reshapes

| Code | Logic | Resulting Shape |
| --- | --- | --- |
| `arr2.reshape(1, 3)` | **Explicit:** You strictly demand 1 row and 3 columns. | `(1, 3)` |
| `arr2.reshape(-1, 3)` | **Implicit:** You demand 3 columns and let NumPy calculate the rows. | `(1, 3)` |

**Why do both produce a 2D array?**
Because you provided **two** arguments in the parentheses, you are forcing the array into a 2D structure.

* Original `arr2`: `[1, 2, 3]` (Shape: `(3,)`)
* Reshaped `arr2`: `[[1, 2, 3]]` (Shape: `(1, 3)`)

---

### 3. When is `-1` actually useful?

The `-1` becomes a lifesaver when you have a massive dataset and you don't want to do the mental math.

Imagine you have an array with **784** elements (a flattened 28x28 image).

* If you want to turn it into a column vector, you could type `.reshape(784, 1)`.
* Or, you could simply type `.reshape(-1, 1)`.

If your data size changes later (e.g., to 1000 elements), the `.reshape(-1, 1)` code will **still work** without you having to update the number `784` to `1000`.

### Important Constraint

You can only use `-1` **once** in a reshape command. If you try `arr.reshape(-1, -1)`, NumPy will throw an error because it doesn't have enough information to solve the equation!

Would you like to see how to use `-1` to quickly flatten any multi-dimensional array back into a single 1D line?

In [13]:
4.
a = np.eye(4)
print(a)
a = a.reshape(16,)
print(a)
print(a.ndim)
print(a.shape)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
1
(16,)


In [21]:
5.
b = np.random.rand(3,4)
print(b)
# random.rand array method 
# Range: The values generated are >=0 and < 1.
# Distribution: It is "Uniform," meaning every value between 0 and 1 has an equal chance of being picked.

b = b.reshape(12,1)
print(b)


[[0.61253699 0.25175945 0.61574519 0.08910399]
 [0.56639338 0.15062017 0.85659752 0.37009477]
 [0.92402948 0.15922954 0.14057166 0.64064854]]
[[0.61253699]
 [0.25175945]
 [0.61574519]
 [0.08910399]
 [0.56639338]
 [0.15062017]
 [0.85659752]
 [0.37009477]
 [0.92402948]
 [0.15922954]
 [0.14057166]
 [0.64064854]]


In [25]:
6.
b.ravel()


array([0.61253699, 0.25175945, 0.61574519, 0.08910399, 0.56639338,
       0.15062017, 0.85659752, 0.37009477, 0.92402948, 0.15922954,
       0.14057166, 0.64064854])

In [26]:
7. 
# reshape fails when the element doesn't match the shape of matrix
# for example if there is array of 5 element and we want to convert it into 
# 3 X 3 matrix , then reshape method will through error becuse in 3 X 3 matrix
# have 9 element. 

7.0

In [ ]:
9. # convertin 3d array into 2d array
three_d = np.ones((2,3,3))
print(three_d)
print()
three_d = three_d.reshape(6,3)
print(three_d)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


10.
While both `reshape(-1)` and `ravel()` will transform your 2D array into a 1D array, the difference lies in **memory efficiency** and the **intent** of the code.

Here is the breakdown:

### 1. The Functional Difference

* **`ravel()`**: This is a specialized function designed specifically for "flattening" an array. It is generally faster and more readable when your only goal is to turn a multi-dimensional array into a 1D version.
* **`reshape(-1)`**: This is a general-purpose tool. While it achieves the same result, you are using a "wildcard" logic to force the dimensions.

---

### 2. Memory: View vs. Copy

This is the most important technical distinction:

| Method | Behavior | Memory Usage |
| --- | --- | --- |
| **`ravel()`** | Always attempts to return a **view** of the original array. | **Memory Efficient:** It doesn't create a new array; it just points to the original data in a new way. |
| **`reshape(-1)`** | Returns a **view** whenever possible. | **Memory Efficient:** Similar to ravel, but used in broader contexts. |
| **`flatten()`** | Always returns a **copy**. | **Memory Heavy:** It creates a brand new array in memory. |

> **Warning:** Because `ravel()` returns a **view**, if you change an element in the 1D array, the element in the original 2D array will also change!

---

### 3. Code Example

```python
import numpy as np

arr_2d = np.array([[1, 2], [3, 4]])

# Using ravel
raveled = arr_2d.ravel()

# Using reshape
reshaped = arr_2d.reshape(-1)

# Modify the raveled version
raveled[0] = 99

print(arr_2d) 
# Output: [[99, 2], [3, 4]] 
# Notice the original array CHANGED because ravel created a view!

```

### Summary: Which one should you use?

1. Use **`ravel()`** if you just need a 1D version of your data and want to save memory.
2. Use **`reshape(-1)`** if you are already performing other shape transformations and want to keep your code consistent.
3. Use **`flatten()`** (not mentioned by you, but important) if you want to make sure the original 2D array is **protected** from any changes you make to the 1D version.

Would you like to see how `flatten()` compares to these two in terms of speed?

In [36]:
11.
# No, the original array does not change.

# In NumPy, .reshape() is a method that returns a new view of the data. It does not modify the original array "in-place."

11.0

12.In NumPy, `.reshape()` almost always creates a **view**, not a copy.

This means that instead of duplicating your data in memory, NumPy simply creates a new "window" or "lens" through which to look at the same underlying numbers.

---

### 1. How it Works (Memory Logic)

When you reshape, the physical data (the "buffer") stays exactly where it is in your RAM. NumPy just updates the **metadata**—the instructions that tell it where one row ends and the next begins.

### 2. The "Shared Data" Effect

Because it is a view, if you modify an element in the reshaped array, the **original array will also change**. They are both pointing to the same memory address.

```python
import numpy as np

original = np.array([1, 2, 3, 4])
view_arr = original.reshape(2, 2)

# Change the view
view_arr[0, 0] = 99

print(original) 
# Output: [99, 2, 3, 4] -> The original was modified!

```

---

### 3. When does it create a Copy instead?

While NumPy *prefers* to create a view, there are rare cases where it is forced to create a **copy**. This happens if the memory of the original array is not "contiguous" (meaning the numbers aren't sitting in a perfectly straight line in your RAM).

This usually occurs after you've done advanced slicing or used "fancy indexing."

### 4. How to check for sure

You can use the `.base` attribute to check if an array is a view or its own original data:

| Property | Meaning |
| --- | --- |
| `arr.base` is **None** | It is the original array (owns its data). |
| `arr.base` is **not None** | It is a **view** pointing to a base array. |

---

### Summary Table

| Operation | Result Type | Memory Impact |
| --- | --- | --- |
| `arr.reshape()` | **View** (Usually) | Very low; fast. |
| `arr.ravel()` | **View** (Usually) | Very low; fast. |
| `arr.flatten()` | **Copy** (Always) | Higher; creates new data. |
| `arr.copy().reshape()` | **Copy** | Safest way to avoid changing original. |

[Image comparing NumPy view vs copy memory allocation]

### Pro Tip

If you want to reshape an array but ensure that the original remains safe and untouched no matter what, always use `.copy()`:

```python
safe_reshape = arr.reshape(2, 2).copy()

```


In [ ]:
14.

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape row-wise (Default)
# You can explicitly say order='C', but it is the default.
row_wise = arr.reshape((2, 3), order='C')

print("Original:", arr)
print("Row-wise Reshape:\n", row_wise)

15.
col_wise = arr.reshape(3,2,order='F')
print("col_wise Reshape:\n", col_wise)


Original: [1 2 3 4 5 6]
Row-wise Reshape:
 [[1 2 3]
 [4 5 6]]
col_wise Reshape:
 [[1 4]
 [2 5]
 [3 6]]


16.
The memory impact of `.reshape()` is remarkably low because, in almost all cases, it creates a **view** rather than a **copy**. This makes it an "O(1)" operation—it takes the same tiny amount of time regardless of whether your array has 10 elements or 10 billion.

---

### 1. Zero Data Movement

When you reshape an array, NumPy does **not** move, copy, or rewrite the actual numbers in your computer's RAM.

* **The Data Buffer:** The physical block of memory where your numbers live remains untouched.
* **The Metadata:** NumPy only creates a new "Array Header." This header is a tiny piece of data that stores the new `shape`, `strides`, and `dimensions`.

### 2. Strides: The Secret to Efficiency

To understand how NumPy "changes" the shape without moving data, you have to understand **Strides**. Strides are instructions that tell NumPy how many bytes to skip in memory to get to the next element.

* In a **1D array**, to get to the next element, you skip 8 bytes (for a float64).
* In a **2D array**, to move down one row, the "stride" tells NumPy to skip exactly the number of bytes contained in one full row.

By simply changing these "skipping instructions," NumPy can make a flat list of numbers appear like a cube, a matrix, or a column vector instantly.

---

### 3. Memory Comparison: Reshape vs. Copy

| Operation | Memory Impact | Logic |
| --- | --- | --- |
| `arr.reshape(new_shape)` | **Negligible** | Creates a new header (~100 bytes) pointing to existing data. |
| `arr.copy()` | **Heavy** | Allocates a brand new block of RAM and duplicates every number. |
| `arr.flatten()` | **Heavy** | Always creates a copy, doubling memory usage for that data. |
| `arr.ravel()` | **Negligible** | Usually creates a view (similar to reshape). |

---

### 4. When does Reshape use MORE memory?

There is one specific scenario where `.reshape()` can fail to create a view and will be forced to create a copy: **Non-contiguous memory.**

If you have taken a complex "slice" of an array (e.g., `arr[::2, ::2]`), the numbers are no longer sitting side-by-side in memory. If you try to reshape this "fragmented" data into certain shapes, NumPy cannot find a mathematical way to use strides to represent it. It will then:

1. Allocate a new block of memory.
2. Copy the data into a "contiguous" (straight) line.
3. Perform the reshape.

### 5. How to Check Memory Sharing

You can verify if two arrays share the same memory (meaning the reshape had no data impact) using `np.shares_memory()`:

```python
import numpy as np

a = np.arange(1000000) # Large array
b = a.reshape(1000, 1000)

print(np.shares_memory(a, b)) # Returns True

```

Would you like to see how to check the exact byte-size of your array's metadata versus its data buffer?

Random method 

rng = np.random.default_rng()

# For integers
integers = rng.integers(low=0, high=10, size=5)

# For floats in a range
floats = rng.uniform(low=0, high=10, size=5)