
1. Compute dot product of two 1D arrays.

2. Explain dot product mathematically.

3. Compute matrix multiplication using dot.

Compute same using @.

Difference between * and dot.

Why element-wise multiplication fails for matrix math.

Predict shape of dot product.

Multiply (2×3) matrix with (3×2) matrix.

Why inner dimensions must match?

Perform vector–matrix multiplication.

Perform matrix–vector multiplication.

Chain two matrix multiplications.

Use dot after transpose.

Compute dot product after slicing.

Explain dot product in data science.

Compare np.dot() and @.

Predict dot error without running code.

Use dot to compute weighted sum.

Dot product vs cosine similarity (conceptual).

Real-world use of dot in ML.

Compute row-wise dot product.

Compute column-wise dot product.

Dot product with boolean arrays.

Dot product on reshaped arrays.

Explain memory flow in dot operation.

In [1]:
import numpy as np



In [7]:
1.
arr1 = np.arange(50,0,-5)
arr2 = np.arange(1,51,5)
print(arr1 * arr2)
print((arr1 * arr2).sum())
print()
print(arr1.dot(arr2))
print(arr2.dot(arr1))


[ 50 270 440 560 630 650 620 540 410 230]
4400

4400
4400


2.
The dot product is a fundamental operation between two vectors that yields a scalar value, capturing both their magnitudes and the angle between them.

## Geometric Definition
The dot product of vectors \(\vec{a}\) and \(\vec{b}\) is \(\vec{a} \cdot \vec{b} = |\vec{a}| \, |\vec{b}| \cos \theta\), where \(\theta\) is the angle between them  [cuemath](https://www.cuemath.com/algebra/dot-product/). This formula shows it equals zero when vectors are perpendicular (\(\cos 90^\circ = 0\))  [cuemath](https://www.cuemath.com/algebra/dot-product/). For parallel vectors, it reaches a maximum equal to the product of their lengths  [cuemath](https://www.cuemath.com/algebra/dot-product/).

## Algebraic Formula
For vectors \(\vec{a} = (a_1, a_2, \dots, a_n)\) and \(\vec{b} = (b_1, b_2, \dots, b_n)\), the dot product is \(\vec{a} \cdot \vec{b} = a_1 b_1 + a_2 b_2 + \dots + a_n b_n\). In 3D with unit vectors, \(\vec{a} = a_1 \hat{i} + a_2 \hat{j} + a_3 \hat{k}\) and \(\vec{b} = b_1 \hat{i} + b_2 \hat{j} + b_3 \hat{k}\) gives \((a_1 b_1) + (a_2 b_2) + (a_3 b_3)\) since orthogonal unit vectors dot to zero. [cuemath](https://www.cuemath.com/algebra/dot-product/)

## Key Properties
- **Commutative**: \(\vec{a} \cdot \vec{b} = \vec{b} \cdot \vec{a}\). [cuemath](https://www.cuemath.com/algebra/dot-product/)
- **Distributive**: \(\vec{a} \cdot (\vec{b} + \vec{c}) = \vec{a} \cdot \vec{b} + \vec{a} \cdot \vec{c}\). [cuemath](https://www.cuemath.com/algebra/dot-product/)
- It projects one vector onto another, useful in physics for work calculations. For example, \(\vec{a} = (2, 3, 1)\), \(\vec{b} = (5, -2, 3)\) yields \(2\cdot5 + 3\cdot(-2) + 1\cdot3 = 7\). [math.libretexts](https://math.libretexts.org/Bookshelves/Calculus/Calculus_(OpenStax)/12:_Vectors_in_Space/12.03:_The_Dot_Product)

In [ ]:
3.

arr1 = np.array([[1,2,23],[21,31,12],[12,16,18]])
arr2 = np.array([[16,3,41],[19,18,23],[10,20,30]])

print(arr1 * arr2)
print()
print((arr1 * arr2).sum())
print()
print(arr1.dot(arr2))   # solve same as mathematically
print()
print(arr2.dot(arr1))


[[ 16   6 943]
 [399 558 276]
 [120 320 540]]

3178

[[ 284  499  777]
 [1045  861 1934]
 [ 676  684 1400]]

[[ 571  781 1142]
 [ 673  964 1067]
 [ 790 1120 1010]]


In [ ]:
4.
arr = np.array([32,41,51])
ar = np.array([76,35,71])
print("from @ operator :",arr@ar)
print("from dot() product operator :",arr.dot(ar))

#2d with @ or we can use matmul() fucntion both have same result 


print()
print(arr1 @ arr2)

from @ operator : 7488
from dot() product operator : 7488

[[ 284  499  777]
 [1045  861 1934]
 [ 676  684 1400]]


In NumPy, `dot()` and the `@` operator both compute matrix products but differ in behavior and intent, especially across array dimensions.

## Core Functionality
`numpy.dot(a, b)` handles dot products flexibly: for 1D arrays, it's a scalar dot product (e.g., sum of element-wise products); for 2D, matrix multiplication; for higher dimensions, it sums products over the last axis of `a` and second-to-last of `b`. [blog.finxter](https://blog.finxter.com/numpy-operator-vs-np-dot/)
The `@` operator (Python 3.5+) calls `numpy.matmul(a, b)`, designed strictly for matrix multiplication, treating 1D arrays as row/column vectors and enabling clear batch operations on higher-D arrays. [stackoverflow](https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication)
Both yield identical results for 2D arrays, like `np.array([[1,2],[3,4]]) @ np.array([[5,6],[7,8]])` equals `np.dot(...)`. [blog.finxter](https://blog.finxter.com/numpy-operator-vs-np-dot/)

## Key Differences
| Aspect | `np.dot()` | `@` (or `np.matmul()`) |
|--------|------------|-------------------------|
| 1D Arrays | Scalar (e.g., `[1,2] @ [3,4]` → 11)  [stackoverflow](https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication/34142617) | Scalar, same as dot  [community.deeplearning](https://community.deeplearning.ai/t/np-matmul-vs-np-dot/217450) |
| 2D Arrays | Matrix mult. | Matrix mult., more readable  [blog.finxter](https://blog.finxter.com/numpy-operator-vs-np-dot/) |
| 3D+ Arrays | Sums last axis of first with second-last of second  [stackoverflow](https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication/34142617) | Batch matrix mult. (e.g., stacks matrices)  [codecademy](https://www.codecademy.com/article/numpy-matrix-multiplication-a-beginners-guide) |
| Readability | Verbose: `np.dot(a, b)` | Clean: `a @ b`  [blog.finxter](https://blog.finxter.com/numpy-operator-vs-np-dot/) |

## When to Use
Prefer `@` for matrix math in modern code—it's explicit and chainable (e.g., `A @ B @ C`). [blog.finxter](https://blog.finxter.com/numpy-operator-vs-np-dot/)
Use `dot()` for legacy code (pre-Python 3.5) or when needing its unique higher-D summation. [stackoverflow](https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication/34142617)
Example: Vectors `u = np.array([1,2])`, `v = np.array([3,4])`; both give `11`, linking to geometric dot product \(1\cdot3 + 2\cdot4\). [blog.finxter](https://blog.finxter.com/numpy-operator-vs-np-dot/)


5.
| Operation          | Purpose                    | 1D Example Result | 2D Example Result              |
| ------------------ | -------------------------- | ----------------- | ------------------------------ |
| * or np.multiply() | Element-wise mult.         | [3, 8]            | [[5,12],[21,32]] ​   |
| np.dot()           | Dot product / matrix mult. | 11                | [[19,22],[43,50]]    |


In [30]:
7.
8.

arr1 = np.ones((2,3))
arr2 = np.ones((3,2))
arr1[0,0],arr1[0,1],arr1[0,2] = 32,52,21
arr1[1,0],arr1[1,1],arr1[1,2] = 28,19,24

arr2[0,0],arr2[0,1] = 26,17
arr2[1,0],arr2[1,1] = 38,37
arr2[2,0],arr2[2,1] = 10,20
print(arr1,arr2,sep='\n')

# shape prediction after @ multiplication is : 2 x 2
print()
print("product of the matrix is :",arr1 @ arr2,sep='\n')

[[32. 52. 21.]
 [28. 19. 24.]]
[[26. 17.]
 [38. 37.]
 [10. 20.]]

product of the matrix is :
[[3018. 2888.]
 [1690. 1659.]]



## 10. Matrix–Vector Multiplication ()

This is the standard form where the matrix acts as a transformation on a **column vector**.

### Formula

### Copyable Example ()

```text
Matrix A: [[2, 3], [1, 4]]
Vector x: [[5], [6]]

Result:
[(2*5 + 3*6)] = [28]
[(1*5 + 4*6)] = [29]

```

---

## 11. Vector–Matrix Multiplication ()

This setup uses a **row vector** on the left. The result is always a new row vector.

### Formula

### Copyable Example ()

```text
Vector v: [1, 2]
Matrix A: [[10, 20], [30, 40]]

Result:
[(1*10 + 2*30), (1*20 + 2*40)] = [70, 100]

```

---

## Key Dimension Rules

To help you keep track of when these operations are "legal":

* **Matrix–Vector:** 
* **Vector–Matrix:** 

> **Note:** The "inner" numbers must match. If you try to multiply a  vector by a  matrix, the math "breaks" because the dot product runs out of pairs.

Would you like me to provide the code for a  version of these matrices?

In [35]:
12.
arr = np.array([3,4])
print(arr1)
print()
print(arr2)
print()
print(arr)
print()
result = arr1 @ arr2
print(result)
final_result = result.dot(arr)
print()
print("Final result :",final_result)

[[32. 52. 21.]
 [28. 19. 24.]]

[[26. 17.]
 [38. 37.]
 [10. 20.]]

[3 4]

[[3018. 2888.]
 [1690. 1659.]]

Final result : [20606. 11706.]


In [41]:
13.
a = np.array([[23,41,52],[65,72,88]])

print(a)
transposed = a.T
print(transposed)
a1 = np.array([5,6,7])

result = np.dot(a,a1)
print("result is :",result)

[[23 41 52]
 [65 72 88]]
[[23 65]
 [41 72]
 [52 88]]
result is : [ 725 1373]
