**Question number :**

**Question 1:** Create a boolean mask for values > 10.

**Question 2:** Apply boolean mask to extract values.

**Question 3:** Replace values using boolean mask.

**Question 4:** Count values satisfying condition.

**Question 5:** Use multiple conditions with mask.

**Question 6:** Explain why mask length must match array.

**Question 7:** Apply boolean mask on 2D array.

**Question 8:** Mask rows based on condition.

**Question 9:** Mask columns based on condition.

**Question 10:** Use mask to handle missing values.

**Question 11:** Explain mask vs if-else logic.

**Question 12:** Create mask using logical operators.

**Question 13:** Use mask for filtering real data.

**Question 14:** Predict output shape after masking.

**Question 15:** Why masks are essential in Pandas later?

In [2]:
import numpy as np

In [3]:
1.
random = np.random.default_rng()

arr = random.integers(1,100,20)
print(arr)

mask = (arr > 50)

print(mask)


[73 44 21 66 85  4 34 49 99  3 46  8 81 41 53 50 51 96 65 63]
[ True False False  True  True False False False  True False False False
  True False  True False  True  True  True  True]


In [4]:
2.
filtered_arr = arr[mask]
print(filtered_arr)


[73 66 85 99 81 53 51 96 65 63]


In [5]:
3.
a = np.linspace(1,50,10,dtype=int)
print(a)
mas = a > 10 
a[mas] = 100
print(a)
print(len(a))

4.
count = np.sum(a > 10)
print(count)

[ 1  6 11 17 22 28 33 39 44 50]
[  1   6 100 100 100 100 100 100 100 100]
10
8




| Method | Syntax | Best Use Case |
| --- | --- | --- |
| **`np.sum(mask)`** | `np.sum(arr > 10)` | Standard use, very readable. |
| **`np.count_nonzero(mask)`** | `np.count_nonzero(arr > 10)` | Best performance for very large arrays. |
| **`len(arr[mask])`** | `len(arr[arr > 10])` | **Avoid.** This creates a copy of the data just to count it, which wastes memory. |



In [6]:
5.
ar = random.integers(1,50,16)
m = (ar > 10) & (ar < 45)
print(ar)
print(ar[m])

[36 23 35 47 12 49 19 23 15 38 12 47  6 47 42 37]
[36 23 35 12 19 23 15 38 12 42 37]


# 6. Why Mask Length Must Match Array

A boolean mask acts like a stencil or template. For the operation to work, every single "slot" in the array must have a corresponding "True" or "False" instruction in the mask.

## One-to-One Mapping

When you apply a mask, NumPy performs an element-wise check:
- It looks at index 0 of the array and index 0 of the mask simultaneously
- If the mask at index 0 is `True`, the element is kept
- If the mask at index 0 is `False`, the element is discarded

## What Happens with Mismatched Lengths

If the mask is shorter or longer than the array, NumPy encounters an index that exists in one but not the other. This breaks the mapping logic, resulting in an `IndexError`.

If you attempt to use a mask with a mismatched length, Python will raise: **"Boolean index did not match indexed array"**

In [11]:
7.
two_d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_d)
mask1 = two_d > 4
print(mask1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False  True  True]
 [ True  True  True]]


In [20]:
8.
arr = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35]
])
row_avg = arr.mean(axis=1,dtype=int)
print(row_avg)
msk2 = row_avg > 70
c = arr[msk2]
print(c)


[84 53 91 35]
[[78 85 90]
 [88 92 95]]


In [24]:
9.
col_max = arr.max(axis=0)
msk2 = col_max > 90
d = arr[:,msk2]
print(d)

[[85 90]
 [60 55]
 [92 95]
 [40 35]]


In [34]:
10.
data = np.array([56,np.nan,93,23,np.nan,85, 92,4,28,18,70,np.nan])

mask = np.isnan(data)
print(mask)

mean = np.nanmean(data,)  # nanmean is nan safe method mean method give result nan becuase x + nan = nan
data[mask] = mean
data

[False  True False False  True False False False False False False  True]


array([56.        , 52.11111111, 93.        , 23.        , 52.11111111,
       85.        , 92.        ,  4.        , 28.        , 18.        ,
       70.        , 52.11111111])

11.
The fundamental difference between NumPy **masking** and standard Python **if-else logic** is the difference between **Vectorization** and **Iteration**.

### 1. Vectorized (Mask) vs. Iterative (If-Else)

In a standard **if-else** loop, Python examines one element at a time, decides what to do, and then moves to the next. In **masking**, NumPy looks at the entire array as a single block and applies the condition to all elements simultaneously at the CPU level.

| Feature | If-Else Logic (Python) | Masking (NumPy) |
| --- | --- | --- |
| **Process** | **Sequential:** One by one. | **Parallel:** All at once. |
| **Speed** | Slow (High overhead). | Blazing fast (C-level execution). |
| **Syntax** | Verbose (requires a loop). | Concise (single line). |
| **Result** | Usually a new list. | A "view" or a filtered array. |

---

### 2. Logic Flow Comparison

To illustrate the difference, let’s look at how both systems handle the task: *"Find all numbers greater than 10."*

#### **Standard Python (If-Else)**

1. Pick the first number.
2. **Ask:** "Is this > 10?"
3. If yes, add to a new list.
4. Repeat for the next 1,000,000 numbers.

#### **NumPy (Masking)**

1. Create a "stencil" (the mask) the same size as the array.
2. Lay the stencil over the data.
3. The "True" holes in the stencil let the data through; the "False" blocks hide it.

---

### 3. The Performance Gap

The reason we avoid `if-else` in NumPy is the **"Python Tax."**

* Each time a Python loop runs, the interpreter has to check the object type, handle memory pointers, and manage the loop counter.
* A NumPy mask ignores the Python interpreter and uses **SIMD (Single Instruction, Multiple Data)**. This allows the computer's processor to perform the "is it > 10?" check on multiple numbers in a single clock cycle.

### 4. Code Comparison

**Python way (Loop + If):**

```python
# Slow and clunky
result = []
for x in my_list:
    if x > 10:
        result.append(x)

```

**NumPy way (Mask):**

```python
# Fast and elegant
result = arr[arr > 10]

```

### 5. When to use which?

* **Use If-Else:** When the logic is extremely complex and depends on external factors (e.g., "If the value is > 10 AND the current time is after 5 PM AND the user is logged in...").
* **Use Masking:** For any mathematical or data-driven condition. Even complex logic can often be written as a mask using `&` (and) and `|` (or).

Would you like to see how to use **`np.where()`**, which acts like a vectorized "If-Else" statement (If True, do A; else, do B)?

In [26]:
12.
an_arr = np.array([56,62,17,1,77,92,84,83,36,28,5,728,2,28,65,88,99,356,86])

logical_mask = (an_arr > 50) & (an_arr < 90)
fl = an_arr[logical_mask]
print(fl)


[56 62 77 84 83 65 88 86]


In [27]:
13.


13.0

15.
Think of a **mask** in Pandas as a custom-made stencil. If you want to paint only the stars on a canvas, you lay down a stencil that covers everything else. In data terms, a mask tells Pandas exactly which rows to "paint" (manipulate) and which to ignore.

Here is why they are a fundamental part of the Pandas toolkit.

---

## 1. Vectorized Filtering (Speed)

Instead of writing a slow `for` loop to check every row, masks allow you to perform **vectorized operations**. When you apply a condition, Pandas uses highly optimized C code under the hood to evaluate the entire column at once.

* **How it works:** You create a Boolean Series (the mask) and then apply it to the DataFrame.

```python
# The Mask
mask = df['age'] > 25

# The Application
result = df[mask]

```

## 2. Precise Data Cleaning

Masks are the cleanest way to handle outliers or "garbage" data. Using the `.loc` indexer with a mask allows you to target specific cells for replacement without affecting the rest of the dataset.

* **Example:** If you have a "Salary" column and want to cap all values over 100k to exactly 100k, a mask identifies those specific rows instantly.

## 3. Conditional Logic (The `np.where` Alternative)

Often, you need to create a new column based on the values of another. Masks make this readable and efficient.

| Situation | Mask Logic |
| --- | --- |
| **Categorization** | Identify "High Spenders" vs "Low Spenders" |
| **Null Handling** | Isolate rows where data is missing to fill them specifically |
| **Multi-criteria** | Combine conditions using bitwise operators: `&` (and), ` |

## 4. Memory Efficiency

By using a mask, you aren't necessarily creating a whole new copy of the data immediately; you are creating a **view** or a filtered subset. This is crucial when working with large datasets (hundreds of thousands of rows) where duplicating the data would spike your RAM usage.

---

### Pro-Tip: The Tilde (`~`) Operator

The tilde is the "secret weapon" of masking. It flips your mask. If you have a mask that finds all "Active" users, `~mask` instantly gives you all "Inactive" users. It saves you from writing the inverse logic all over again.

> **Note:** Always wrap your individual conditions in parentheses when combining masks, like `df[(df['a'] > 1) & (df['b'] < 5)]`, or Python's operator precedence will throw a `ValueError`.

---

Would you like me to write a quick code snippet showing how to combine multiple masks for a complex filtering task?