1. Select specific elements using index list.

2. Reorder array using fancy indexing.

3. Select non-contiguous elements.

4. Extract specific rows using index list.

5. Extract specific columns using index list.

6. Compare fancy indexing vs slicing.

7. Why fancy indexing returns a copy?

8. Modify fancy-indexed output — does original change?

9. Combine fancy indexing with boolean mask.

10. Real-world use case of fancy indexing in analytics.

While they can sometimes achieve the same result, the "under the hood" behavior of slicing versus fancy indexing is quite different. The biggest distinction lies in **Memory Management** (Views vs. Copies) and **Flexibility**.

---

## 1. The Core Differences

| Feature | Standard Slicing | Fancy Indexing |
| --- | --- | --- |
| **Syntax** | `a[start:stop:step]` | `a[[index_array]]` |
| **Memory** | Returns a **View** | Returns a **Copy** |
| **Performance** | Extremely fast (no data moved) | Slower (new memory allocated) |
| **Output Order** | Must be sequential/regular | Can be any order or repeated |

---

## 2. Views vs. Copies (The Memory Trap)

This is the most critical distinction for performance and bug-squashing.

### Slicing (View)

Slicing creates a **view**. The new variable points to the **same memory** as the original. If you change the slice, the original array changes too.

```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

sub = arr[0:3]
sub[0] = 99

print(arr) # Output: [99, 2, 3, 4, 5] (Original changed!)

```

### Fancy Indexing (Copy)

Fancy indexing creates a **copy**. It extracts the values and puts them in a brand-new spot in memory.

```python
arr = np.array([1, 2, 3, 4, 5])

# Using a list of indices
sub = arr[[0, 1, 2]] 
sub[0] = 99

print(arr) # Output: [1, 2, 3, 4, 5] (Original stays safe!)

```

---

## 3. Visualizing 2D Behavior

Slicing and fancy indexing behave very differently when you move into two dimensions.

* **Slicing** preserves the "grid" structure. `arr[:2, :2]` always gives you a rectangular sub-section.
* **Fancy Indexing** allows for "point-of-interest" selection. If you pass `arr[[0, 1, 2], [2, 1, 3]]`, NumPy pairs the indices to pick specific coordinates: `(0,2)`, `(1,1)`, and `(2,3)`.

---

## 4. When to use which?

* **Use Slicing** when you need a regular sub-section (like "every 2nd row") and want to save memory. It is the gold standard for large datasets because it doesn't duplicate data.
* **Use Fancy Indexing** when you need to "shuffle" data, pick non-contiguous elements (like rows 0, 5, and 9), or filter data based on conditions (Boolean masking).

---

Would you like to see how **Boolean indexing** works? It's a type of fancy indexing where you use `True`/`False` values to filter data.

In [1]:
import numpy as np


In [3]:
1.
arr = np.array([5,6,6,7,2,5,4,8,6,3,2,6])
index = [1,2,3,7,8]
print(arr[index])

[6 6 7 8 6]


In [10]:
2. 
a = np.arange(1,11)
a
# reverse usung fency index
b = [9,8,7,6,5,4,3,2,1,0]

rev_a = a[b]
print(rev_a)

[10  9  8  7  6  5  4  3  2  1]


In [28]:
3.

to_d = np.array([[23,89,53],[1,24,15],[82,39,26]])

print(to_d)
print()
i = [1,2]

print(to_d[i])

4. 
i1 = [0,2]
print(to_d[:,i1])

[[23 89 53]
 [ 1 24 15]
 [82 39 26]]

[[ 1 24 15]
 [82 39 26]]
[[23 53]
 [ 1 15]
 [82 26]]


In [31]:
9.
scores = np.array([
    [85, 92, 70, 45, 60],  # Alice
    [40, 55, 38, 90, 42],  # Bob
    [75, 80, 85, 88, 91],  # Charlie
    [62, 58, 40, 30, 55],  # David
    [95, 99, 92, 98, 100]  # Eve
])

mask = scores[:,0] > 70
student_greater_then_70 = scores[mask]

# We want columns 4 (Art) and 3 (History) specifically
col_indices = [4, 3] 

# Apply to the already filtered students
result = student_greater_then_70[:, col_indices]

print("printing reverse of those student with marks greater then 70 in maths :",result,sep='\n')

printing reverse of those student with marks greater then 70 in maths :
[[ 60  45]
 [ 91  88]
 [100  98]]


10.

## 1. Computer Vision: Pixel Manipulation
In image processing, images are stored as 3D arrays ($Height \times Width \times Channels$). Fancy indexing is used to crop, shuffle, or mask specific regions of an image.

* **Usecase:** Shuffling image patches for data augmentation in machine learning.
* **How it works:** You create an array of random indices representing rows and columns, then apply them to the image array to rearrange pixels or blocks instantly.



---

## 2. Machine Learning: Train-Test Splitting
When preparing data for a model, you often need to shuffle your dataset and split it into training and testing sets.

* **Usecase:** Selecting a random 80% subset of 1 million rows.
* **The Logic:**
    1.  Generate a shuffled array of integers from $0$ to $n-1$.
    2.  Use the first $80\%$ of those integers as a "fancy index" to pull the training rows.
    3.  This avoids slow loops and keeps the data structure intact.

---

## 3. Signal Processing: Removing Outliers
In sensor data (like GPS or heart rate monitors), you often get "noise" or extreme values that need to be clamped or removed.

* **Usecase:** Clipping all values that exceed a certain threshold.
* **The Logic:** You can use boolean fancy indexing to find all indices where $Value > Threshold$ and replace them with the maximum allowable value in one line of code.

---

## 4. Digital Marketing: Targeted Filtering
In large datasets (like a CSV of 500,000 customers), you might want to extract specific groups based on a list of IDs.

* **Usecase:** Pulling records for a specific "High-Value" list of 5,000 Customer IDs.
* **The Logic:** Instead of iterating through the whole database, you pass the array of 5,000 IDs as a fancy index to the DataFrame, returning only the relevant rows instantly.

---

## 5. Monte Carlo Simulations
In finance or physics, simulations often involve selecting random paths or outcomes from a distribution.

* **Usecase:** Sampling 10,000 random scenarios from a pool of 1,000,000 possible market outcomes.
* **Why it's "fancy":** You can use an array of randomly generated indices to "pluck" scenarios out of the pool to calculate the average risk or $Value\ at\ Risk\ (VaR)$.

---

### Summary Table: Why use it?

| Feature | Standard Indexing | Fancy Indexing |
| :--- | :--- | :--- |
| **Speed** | Slow (requires loops) | **Very Fast** (vectorized) |
| **Complexity** | High (more lines of code) | **Low** (compact syntax) |
| **Flexibility** | Sequential access only | **Non-sequential** (any order) |
| **Output** | Single value or slice | **Custom-shaped** arrays |

