**Questions :**
1. Extract first 5 elements from a 1D array.

2. Extract last 3 elements using slicing.

3. Extract every second element.

4. Reverse an array using slicing.

5. Slice rows from a 2D array.

6. Slice columns from a 2D array.

7. Extract a sub-matrix from a matrix.

8. Explain slicing syntax start:stop:step.

9. Modify a slice and observe original array.

10. Why slicing returns a view?

11. Slice alternate rows from matrix.

12. Slice alternate columns from matrix.

13. Slice a diagonal block.

14. Predict slice output shape mentally.

15. Slice negative indices.

16. Combine slicing on rows and columns.

17. Use slicing to zero out part of array.

18. Why slicing is faster than loops?

19. Slice a time-series array.

20. Explain slicing vs indexing difference.

IN slicing the left index is start from 0 to n and from right index start fromm -1 to -n

In [1]:
import numpy as np 

In [2]:
1. 
rng = np.random.default_rng()
new_arr = rng.integers(1,50,20)
new_arr

array([ 8, 37, 41, 25, 33, 41, 29,  6, 18, 12,  2,  3, 19, 40,  1, 25,  4,
       41, 32,  1])

In [3]:
new = new_arr[0:5]
new

array([ 8, 37, 41, 25, 33])

In [4]:
2.

n = int(input("Enter the size of array :"))

arr = rng.integers(1,100,n)
print(arr)
sliced_arr = arr[n-3:n]
sliced_arr
# ORR

[97 70 96 65 37  8  2 86 10 40]


array([86, 10, 40])

In [5]:
2.
print(new_arr)
x = new_arr[-3:]
x

[ 8 37 41 25 33 41 29  6 18 12  2  3 19 40  1 25  4 41 32  1]


array([41, 32,  1])

In [6]:
3.
print(new_arr)
z = new_arr[0::2]
z

[ 8 37 41 25 33 41 29  6 18 12  2  3 19 40  1 25  4 41 32  1]


array([ 8, 41, 33, 29, 18,  2, 19,  1,  4, 32])

In [7]:
4. 
new_arr
reverse = new_arr[::-1]
reverse

array([ 1, 32, 41,  4, 25,  1, 40, 19,  3,  2, 12, 18,  6, 29, 41, 33, 25,
       41, 37,  8])

In [25]:
5. 
ar = np.diag([1,2,3,4])
ar
row_ar = ar[0::2]
print(row_ar)
6.
col_arr = ar[:,2]
print(col_arr)

7.
sub_matrix = ar[0:2,0:2]
print(sub_matrix)

[[1 0 0 0]
 [0 0 3 0]]
[0 0 3 0]
[[1 0]
 [0 2]]


8.
To extract a column from a 2D NumPy matrix, you use the syntax `matrix[row_slice, column_index]`.

### 1. Basic Column Extraction

To get an entire column, you use a colon `:` for the rows (which means "select all rows") and then specify the index of the column you want.

```python
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Extract the second column (index 1)
col_1 = matrix[:, 1]

print(col_1) 
# Output: [20, 50, 80]

```

---

### 2. Common Slicing Variations

The comma separates the **row operations** from the **column operations**.

| Goal | Syntax | Result (from example above) |
| --- | --- | --- |
| **First Column** | `matrix[:, 0]` | `[10, 40, 70]` |
| **Last Column** | `matrix[:, -1]` | `[30, 60, 90]` |
| **Multiple Columns** | `matrix[:, 0:2]` | Columns 0 and 1 as a 2D matrix |
| **Specific Rows in a Col** | `matrix[0:2, 1]` | `[20, 50]` (First two rows of col 1) |

---

### 3. Important: 1D vs. 2D Output

When you extract a single column using an integer index (like `1`), NumPy returns a **1D array**. If your Machine Learning model requires a 2D column vector, you have two choices:

* **Option A (The Slice Trick):** Use `1:2` instead of just `1`.
* **Option B (The `newaxis` Trick):** Add an extra dimension manually.

```python
# Returns 2D shape (3, 1) instead of 1D shape (3,)
col_2d = matrix[:, 1:2] 

# Alternatively, using None or np.newaxis
col_2d_alt = matrix[:, 1, np.newaxis]

```

### 4. Memory Reminder

Just like the other slices we discussed, extracting a column creates a **view**, not a copy. If you change a value in your extracted column, the value in the original matrix will change too!

Would you like to see how to extract **every other column** using the "step" part of the slice? 


In [32]:
9.
another = np.linspace(0,100,10,dtype=int)
one = another[0:5]
print(one)
one[2] = 90
print(one)
print(another)
# NOTE : original array also changed when we changed the sliced array 

[ 0 11 22 33 44]
[ 0 11 90 33 44]
[  0  11  90  33  44  55  66  77  88 100]


In [33]:
10.
# Slicing returns a view because of NumPy's core design philosophy: performance and memory efficiency.

# When you slice an array, NumPy doesn't want to waste time or RAM duplicating data that already exists in your computer's memory
# . Instead, it creates a new "window" into the existing data.

10.0

In [53]:
11.
dd = np.diag([1,2,3,4,6,7])
print(dd)
print()

rows = dd[::2]
print(rows)
print()
12.
column = dd[::,::2]
print(column)
print()
13.
diagnol = dd[0:4:,0:4:]
print(diagnol)
print()
15.
negative = dd[-1:-3:-1,0:3]
print(negative)


[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 7]]

[[1 0 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 0 6 0]]

[[1 0 0]
 [0 0 0]
 [0 3 0]
 [0 0 0]
 [0 0 6]
 [0 0 0]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[[0 0 0]
 [0 0 0]]


16, 17, 18, 19, 20
Here is the breakdown of these advanced NumPy concepts, continuing your deep dive into the library.

---

### 16. Combine Slicing on Rows and Columns

To slice both dimensions at once, you use the format `matrix[row_start:row_stop, col_start:col_stop]`.

```python
import numpy as np

# Create a 4x4 matrix
matrix = np.array([[10, 11, 12, 13],
                   [20, 21, 22, 23],
                   [30, 31, 32, 33],
                   [40, 41, 42, 43]])

# Extract the "inner square" (middle two rows and middle two columns)
inner_square = matrix[1:3, 1:3]

print(inner_square)
# Output:
# [[21, 22]
#  [31, 32]]

```

---

### 17. Use Slicing to Zero Out Part of an Array

Because slicing returns a **view**, you can perform a "broadcast assignment" to modify a specific section of the original array instantly.

```python
# Zero out the first two rows
matrix[:2, :] = 0

print(matrix)
# The first two rows are now all zeros, others remain untouched.

```

---

### 18. Why Slicing is Faster than Loops?

Slicing is significantly faster because of **Vectorization**.

* **Loops (Python level):** When you use a `for` loop, Python has to check the data type of every single element, handle bounds checking, and iterate in a high-level environment. This is slow "overhead."
* **Slicing (C level):** NumPy performs the slicing operation in compiled **C code**. It calculates the memory offset once and then uses low-level CPU instructions to access the data buffer. This avoids the "Python tax" entirely.

---

### 19. Slice a Time-Series Array

In time-series data, you often want to look at "windows" of time. If your array represents daily data, you can slice specific weeks or use "steps" to look at specific days (e.g., every Monday).

```python
# 30 days of temperature data
temp_data = np.random.randint(20, 35, size=30)

# Slice the second week (indices 7 to 13)
week_2 = temp_data[7:14]

# Slice every 7th day (e.g., all Mondays)
mondays = temp_data[::7]

```

---

### 20. Slicing vs. Indexing Difference

While they look similar, the key difference lies in the **shape** of the output.

| Feature | Indexing (`arr[0]`) | Slicing (`arr[0:1]`) |
| --- | --- | --- |
| **Logic** | Grabs a **single** element. | Grabs a **range** of elements. |
| **Dimension** | Usually **reduces** dimensionality (e.g., 2D  1D). | **Preserves** dimensionality (e.g., 2D  2D). |
| **Result** | Returns the value at that spot. | Returns a "view" of that segment. |

**Example of the difference:**

* `matrix[0, :]` returns a **1D array** (the first row).
* `matrix[0:1, :]` returns a **2D array** with one row (a row vector).

Would you like to see how to use **Boolean Indexing** to extract values based on a condition, like "all numbers greater than 50"?
